### ISSUE TITLE
1.16.5 Beta 29 Crash when breaking DT sapling

### ISSUE THREAD

**Issue by Aspurgus** [ferreusveritas/Dynamic-Trees#655] opened 2022-01-17 01:56 UTC
**Description**
Client crash when breaking DT saplings on a 1.16.5 Forge server

**To Reproduce**
Place an oak tree seed then break the sapling

This happened both with and without Optifine

**Crashes**
https://gist.github.com/Aspurgus/9d4e5665a4f0fe488c55fb76d5385424

**Comment by TheeMrCheeky** [comment] 2022-01-17 02:07
I am getting something similar but i really have NO idea what is causing it cause a few mods had updates and I forget what all ones. All i know is since i updated DT and a few others everytime i break the base of a tree it crashes the game (imma do some testing and get back)

**Comment by TheeMrCheeky** [comment] 2022-01-17 02:17
DynamicTreesPlus-1.16.5-0.1.0-Beta10.jar
DynamicTrees-1.16.5-0.10.0-Beta26.jar
These 2 have to issues 
but every update after these versions crashes when cutting down a tree on 1.16.5 , forge version 36.2.22
Possibly a mod incompatibility? Not sure..

**Comment by Harleyoc1** [comment] 2022-01-17 18:39
I can't reproduce this so best guess is it is a mod incompatibility.

**Comment by Harleyoc1** [comment] 2022-01-17 20:36
Huh, just noticed you're playing on a server there where I only tested this in Singleplayer. I think I know what the cause is.

**Comment by Harleyoc1** [comment] 2022-01-17 20:48
Should be fixed now, will release beta 30 shortly.

**Closed as completed by Harleyoc1** 2022-01-17 20:48 UTC
Labels: bug, 1.16.5
