### ISSUE TITLE
I can't run my modded minecraft in version 1.18.2 forge when the mod Dynamic trees and with other mods

### ISSUE THREAD

**Issue by SnayZi** [ferreusveritas/Dynamic-Trees#794] opened 2023-07-19 17:47 UTC
I can't run my modded minecraft in version 1.18.2 forge when the mod Dynamic trees and with other mods

i use this version of the mod : DynamicTrees-1.18.2-1.0.3

I use the version 1.18.2 - 40.2.10 of forge

[crash-2023-07-19_19.34.03-fml.txt](https://github.com/DynamicTreesTeam/DynamicTrees/files/12098657/crash-2023-07-19_19.34.03-fml.txt)

![image](https://github.com/DynamicTreesTeam/DynamicTrees/assets/140006099/6471e10b-3682-4263-9300-7dd12cf3b1a6)
![Capture d’écran 2023-07-19 194334](https://github.com/DynamicTreesTeam/DynamicTrees/assets/140006099/c674727e-9f92-48ef-ab69-a0e088f52298)

**Comment by Harleyoc1** [comment] 2023-07-19 18:35
Duplicate of #777

**Closed as completed by Harleyoc1** 2023-07-19 18:35 UTC
Labels: bug

**Comment by Harleyoc1** [comment] 2023-07-19 18:37
Unfortunately DT is incompatible with Hostile Villages at the moment. They must also modify villages and since there's no official way to do this our method is clashing. 

A workaround would be to set `cancelVanillaVillageTrees` to `false` in the common config (located at `config/dynamictrees-common.toml`), though it will mean that vanilla trees will spawn in villages (unless Hostile Villages also removes these - I'm unsure of what it changes).

**Comment by SnayZi** [comment] 2023-07-19 18:54
it doesn't work even by removing it the problem remains the same
