### ISSUE TITLE
Failed to Start with CTM and Other Mods

### ISSUE THREAD

**Issue by SoggieWafflz** [ferreusveritas/Dynamic-Trees#383] opened 2019-12-17 03:40 UTC
**Describe the bug**
When all of my mods are loaded with dynamic trees, it loads fine.
When all of my mods are loaded with CTM, Chisel, and Chisel and Bits, with dynamic trees, Dynamic Trees is the apparent cause of a crash.
When dynamic trees is loaded with only CTM, Chisel, and Chisel and Bits, it loads fine.
When all of my mods are loaded with CTM, Chisel, and Chisel and Bits, without dynamic trees, it loads fine.

**To Reproduce**
The WIP Modpack:
https://mega.nz/#F!nNtBTAaK!p63fLW_vxo7KZ-DiXW0NqA

Try loading 1.12.2 Forge with these mods in the configurations listed above

**Screenshots**

**Crashes**
- Are you running the latest version of Dynamic Trees?(Currently 0.9.6)
Yes
- If you are using the DT Biome O' Plenty Add-on do you have the latest version?(Currently 1.4.1e)
Yes
- If you are using the DT Thaumcraft Add-on do you have the latest version?(Currently 1.4.1e)
No, but I am using Pam's Harvestcraft add-on, with version 1.4.2

crash log: https://pastebin.com/2y2f5D5h

**Comment by SoggieWafflz** [comment] 2019-12-17 03:43
I'm trying to isolate another mod if possible, but the circumstances seemed really weird that both mods worked individually, worked fine alone, but only didn't work with the rest of the pack, so I figured I'd make a post now with what I know while I try and remove other mods

**Comment by kierajreed** [comment] 2019-12-18 05:22
Duplicate of #373. This is being investigated.

**Closed as completed by kierajreed** 2019-12-18 05:22 UTC
