### ISSUE TITLE
Crash on breaking tree

### ISSUE THREAD

**Issue by CactusDuud** [ferreusveritas/Dynamic-Trees#175] opened 2018-12-10 21:28 UTC
[Crash Report](https://paste.dimdev.org/efifoloreg.mccrash)

Playing DynamicTrees-1.12.2-0.9.1d on forge build 2776

**Comment by ghost** [comment] 2018-12-10 21:52
Duplicate of #172

**Closed as completed by ghost** 2018-12-10 21:52 UTC
