### ISSUE TITLE
Crashing at launch

### ISSUE THREAD

**Issue by cookiehow** [ferreusveritas/Dynamic-Trees#861] opened 2024-05-17 12:56 UTC
Crash report: https://www.paste.tc/crash-report-3

My game crashed before it even launches correctly the second I add Dynamic trees or any add-on of it to my mods folder, I tried to see if it was clashing with any other mods and took them all out except Dynamic trees but it still crashes, I also tried 3 different versions of it to see if it was tied to a specific version but still didnt work

**Comment by mitat52** [comment] 2024-06-19 22:38
same issue, all versions of mod for 1.20.1 its all crashes expect just beta3 version opens game but game runs without mod so there no anything about mod. looking for a fix

**Comment by supermassimo** [comment] 2024-06-28 20:30
Please confirm if this still happens

**Comment by mitat52** [comment] 2024-07-02 09:00
> Please confirm if this still happens

still happens

**Comment by supermassimo** [comment] 2024-07-04 14:05
This issue is caused by your system language being Turkish.
To fix this, add the following parameters to your java launch arguments:
`-Duser.country=US -Duser.language=en`

**Comment by supermassimo** [comment] 2024-07-04 14:12
1.20.1-Beta9 will now contain a fix for this

**Closed as completed by supermassimo** 2024-07-04 14:12 UTC
Labels: bug, 1.20.1
