### ISSUE TITLE
Dynamic Trees Failed To Load

### ISSUE THREAD

**Issue by SnowFox3741** [ferreusveritas/Dynamic-Trees#775] opened 2023-04-24 18:41 UTC
**Describe the bug**
When i loaded up my modpack it said Dynamic Trees (DT) failed to load correctly. i checked and all of the mods in my modpack are up to date.

**To Reproduce**
Steps to reproduce the behavior: ?

**Screenshots**
i couldn't figure out how to send or how to screenshot so heres the image link    https://1drv.ms/i/s!Apw7QM1F2oeujjIfuaZYgyfnt64K?e=oIczXV

**Rendering Glitches**
i'm not using Optifine, does Magnesium count as rendering?

**Additional context**
i tried removing the add ons but it still said that DT failed to load correctly. and still says the same the thing even when i updated all the mods.

**Crashes**
i created a gist and i think this is a link?      <script src="https://gist.github.com/SnowFox3741/ce3a75a817af36afdf3b394cb05e37ee.js"></script>

Heres the zip:    [ce3a75a817af36afdf3b394cb05e37ee-f8f133a069dcdb5791b21dba3789ab260cc6475c.zip](https://github.com/DynamicTreesTeam/DynamicTrees/files/11313589/ce3a75a817af36afdf3b394cb05e37ee-f8f133a069dcdb5791b21dba3789ab260cc6475c.zip)

**Mods List**

1. Additional Banners
2. Apple Skin

3. Aquaculture 2
4. Archer's Paradox
5. Artifacts
6. Better Animals Plus
7. Better Animations Collections
8. Better Villages - Forge
9. Biomes O' Plenty
10. Boatload 
11. Caves & Cliffs Backport
12. Charm Reforged
13. Clumps
14. Comforts (Fabric/Forge/Quilt)
15. Cosmetic Armor reworked
16. Curios API (Forge)
17. Doggy Talents
18. Dragons And Pets
19. Dungeon Crawl
20. Dungeons Content
21. Dungeons Enhanced
22. Dungeons Plus
23. Dynamic Trees (DT)
24. DT Biomes o' Plenty
25. DT Neapolitan
26. DT +
27. DT Pam's Harvestcraft
28. Enchantment Descriptions
29. Ensorcellation
30. Fairy Lights
31. First Aid
32. Flight Command
33. Grappling Hook Mod
34. Hwyla
35. Ice and Fire: Dragons
36. Inventory Pets
37. JEI Enchantment Info
38. JEI Integration
39. JourneyMap
40. Just Enough Items (JEI)
41. Just Enough Recources
42. Leap
43. Macaw's Doors
44. Macaw's Fences-Biomes O' Plenty
45. Macaw's Fences and Walls
46. Macaw's Furniture
47. Macaw's Furniture- Biomes O' Plenty
48. Macaw's Paintings
49. Macaw's Roofs
50. Macaw's Roofs-Biomes O' Plenty
51. Macaw's Trapdoors
52. Macaw's Windows
53. Magnesium
54. Magnesium/Rubidium Dynamic Lights
55. More Villagers
56. Mouuse Tweaks
57. MrCrayfish's Furniture Mod
58. MrCrayfish's Gun Mod
59. My Hero Acedemia
60. Mystical Agriculture
61. Neapolitan
62. Neat
63. Obfuscate
64. Pam's Harvestcraft 2 - Crops (PHC)
65. PHC 2- Food Core
66. PHC 2- Food Extended
68. PHC 2- Trees
69. Patchouli
70. Prefab
80. Repurposed Structures
81. Serene Seasons
82. Serene Seasons-Pam's HarvestCraft- Crops Compact
83. Serene Seasons-Pam's HarvestCraft- Trees Compact
84. Spartan & Tinkers' Metals
85. Spartan Shields
86. Spartan Weaponry
87. Spartan Weaponry-Ice And Fire
88. Spartan Weaponry-Twilight Forest
89. Supplementaries
90. The Twilight Forest
91. Useful Backpacks
92. Waila Harvestability
93. Waystones
94. When Dungeons Arise-Forge!
95. Zoo and Wild Animals: Evolved (ZAWA)

**Comment by Harleyoc1** [comment] 2023-04-24 21:40
Duplicate of #724. Again this needs to be fixed on CaveBiome's end.

**Closed as completed by Harleyoc1** 2023-04-24 21:40 UTC
Labels: bug
