### ISSUE TITLE
Dynamic Trees Spawning Issues

### ISSUE THREAD

**Issue by BurlyBeard** [ferreusveritas/Dynamic-Trees#459] opened 2020-11-06 22:03 UTC
**Describe the bug**
In a newly generated world, I am getting both "vanilla" style thick full block style trees, mixed in with the Dynamic style trees. I have both BOP and the BOP Dynamic Trees addons installed. Below is a screen shot of an example as well as a screen shot of the mods that I have installed. I cannot think of anything here that would be causing this issue, but I'm not a developer, so what do I know?!

This is for minecraft 1.12.2.

**Screenshots**
![2020-11-06_15 59 58](https://user-images.githubusercontent.com/74077323/98418727-2d524580-2049-11eb-8145-b7ee778cc533.png)
![Capture](https://user-images.githubusercontent.com/74077323/98418844-668ab580-2049-11eb-9fe3-30134cb275ac.PNG)

**Rendering Glitches**
I am not using Optifine

**Comment by Harleyoc1** [comment] 2020-11-07 01:02
I believe this is being caused by Recurrent Complex. Should be a `nature` option in its config or something along those lines.

Please close the issue if this solves your problem.

**Comment by Harleyoc1** [comment] 2020-11-07 23:49
Going to close this as I believe the above should solve your problem. If it doesn't feel free to re-open the discussion.

**Closed as completed by Harleyoc1** 2020-11-07 23:49 UTC
