### ISSUE TITLE
crash when launching

### ISSUE THREAD

**Issue by SmellyBozoAce** [ferreusveritas/Dynamic-Trees#840] opened 2024-01-26 03:06 UTC
when I launch the game on 1.20.1 forge 47.1.3 it crashes before title screen. https://pastebin.com/d5zJf0N8

**Comment by davidromrell** [comment] 2024-05-01 17:23
issue with modernfix or supermartijn642corelib

**Comment by supermassimo** [comment] 2024-06-28 20:26
Please confirm if this still happens on latest beta

**Comment by supermassimo** [comment] 2024-06-28 20:29
Duplicate of https://github.com/DynamicTreesTeam/DynamicTrees/issues/844

**Closed as completed by supermassimo** 2024-06-28 20:29 UTC
Labels: bug, mod incompatibility, 1.20.1
