### ISSUE TITLE
Particles and sounds doubling

### ISSUE THREAD

**Issue by Danymaddox** [ferreusveritas/Dynamic-Trees#221] opened 2019-02-19 17:46 UTC
**Describe the bug**
Sound and particle doubling

**To Reproduce**
Die to anything except /kill and broke any block. You should see that te particles are doubled and seems like you are destroying more than one block

**Crashes** No crash log, but there you have some info
- I'm using Dynamic Trees 0.9.4

**Mods List**
Dynamic Trees.
I've discovered this bug with bigger modlist, but this mod alone is fine to reproduce it.

Forge: 14.23.5.2815

**Comment by kierajreed** [comment] 2019-02-20 02:29
Possible duplicate of #220.

**Comment by LuminaSapphira** [comment] 2019-02-26 03:23
I can verify that the issue #220 fixes will also occur on death, and is still resolved by the PR.

**Comment by MogTheMoogle** [comment] 2019-03-16 02:48
Can replicate this easily myself.
Also, the trigger is a notch inaccurate. /kill actually does trigger the glitch as well. It appears to get worse on every death, too.

**Comment by Khioni** [comment] 2019-03-16 02:56
**Can effortlessly replicate.**
(MC1.12.2-v0.9.4 / Forge 14.23.5.2768 at the time)

**As far as I've seen from earlier experimentation:**
- With my MC/DynamicTrees/Forge combo, I was able to trigger the glitch with /kill as well.
- The duping gets worse every death, theoretically until you freeze up from sheer particles.
- Save&Quit / Disconnect > Rejoin temporarily fixes the glitch, but dying again resets it to just as bad as it was before, plus the additional stack from the previous line.

I feel like this glitch is quite game-breaking whenever it happens. It turns respawning from a few seconds into a way longer time, depending on how big your modded setup is, as to loophole the glitch, you have to S&Q and rejoin. I have had to wait several minutes to respawn properly since my 1P world would take forever to S&Q to title.

**Comment by LuminaSapphira** [comment] 2019-03-16 17:06
Well since there's still no fix implemented, I built a hotfix binary from my fork. ty MIT license.
https://github.com/CerulanLumina/DynamicTrees/releases/tag/0.9.4-hotfix

**Comment by kierajreed** [comment] 2019-04-21 01:09
Closed by #220.

**Closed as completed by kierajreed** 2019-04-21 01:09 UTC
