### ISSUE TITLE
Error occurs on Dynamic Trees 1.18.2-0.11.0-Beta4 causes crash

### ISSUE THREAD

**Issue by caniplzjustlogin4godsakesthistakesforev** [ferreusveritas/Dynamic-Trees#740] opened 2022-12-11 18:20 UTC
Attached is the log and crash report:
[latest.log](https://github.com/DynamicTreesTeam/DynamicTrees/files/10202895/latest.log)
[crash-2022-12-11_12.16.30-fml.txt](https://github.com/DynamicTreesTeam/DynamicTrees/files/10202897/crash-2022-12-11_12.16.30-fml.txt)

**Comment by Harleyoc1** [comment] 2022-12-12 14:58
Duplicate of #737

**Closed as completed by Harleyoc1** 2022-12-12 14:58 UTC
