### ISSUE TITLE
Can't harvest trees

### ISSUE THREAD

**Issue by robinotwilliams** [ferreusveritas/Dynamic-Trees#517] opened 2021-05-04 11:47 UTC
Minecraft 1.1.6.5
Dynamic Trees 0.10.0 BETA

I can't harvest dynamic trees on my server with this in my modpack, however in Singleplayer everything works perfectly fine as well as Vanilla logs.

Modlist:
Just Enough Resources (JER) (by way2muchnoise)
First Aid (by ichttt)
Create (by simibubi)
Hwyla (by TehNut)
Random Village Names (by Serilum)
Cosmetic Armor Reworked (by LainMI)
Collective (by Serilum)
Structure Gel API (by ModdingLegacy)
Absent by Design (by Lothrazar)
Morpheus (by Quetzi)
Armor Poser (by Mrbysco)
Traveller's Boots (by DenisMasterHerobrine)
Regrowth (by MacTso)
Healing Campfire (by Serilum)
Pam's HarvestCraft 2 - Trees (by pamharvestcraft)
XL Packets (by tfarecnim)
Stoneholm, Underground Villages (Forge) (by TheGrimsey)
Project: Vibrant Journeys (by solis_nova123)
Pam's HarvestCraft 2 - Food Extended (by pamharvestcraft)
FTB Library (Forge) (by FTB)
Enhanced Celestials - Blood Moons & Harvest Moons (by Corgi_Taco)
Quark O' Plenty (by rosy162)
CoFH Core (by TeamCoFH)
Sophisticated Backpacks (by P3pp3rF1y)
Nether Portal Spread (by Serilum)
Druidcraft (by VulpTheHorseDog)
Wall-Jump! [FORGE] (by genandnic)
Abnormals Core (by TeamAbnormals)
Waystones (by BlayTheNinth)
TenshiLib (by flemmli97)
Comforts (Forge) (by TheIllusiveC4)
Areas (by Serilum)
Placebo (by Shadows_of_Fire)
Subterranean Wilderness (by Melonslise)
iChunUtil (by ohaiiChun)
Back Tools (by ohaiiChun)
Reliquary v1.3 (by P3pp3rF1y)
Better Advancements (by way2muchnoise)
Dungeons Plus (by ModdingLegacy)
Double Doors (by Serilum)
Upstream (by Corgi_Taco)
MmmMmmMmmMmm (by bonusboni)
Bookshelf (by DarkhaxDev)
Paragliders (by Tictim)
Eidolon (by elucent_)
UnionLib (by Stereowalker)
Structurize (by H3lay)
Waila Harvestability (by squeek502)
Dynamic Trees - Quark (by supermassimo0310)
Spartan Weaponry (by ObliviousSpartan)
YUNG's API (Forge) (by YUNGNICKYOUNG)
Corpse (by henkelmax)
Two Players One Horse (by Beethoven92)
Ice and Fire: Dragons (by alex1the1666)
Carry On (by Tschipp)
Sit (by bl4ckscor3)
Better Weather - Seasons, Blizzards, and more! (by Corgi_Taco)
Relics (by SSKirillSS)
Curios API (Forge) (by TheIllusiveC4)
Project MMO (by Harmonised_)
Improved Mobs (by flemmli97)
Wawla - What Are We Looking At (by DarkhaxDev)
Dungeon Crawl (by XIROC1337)
Dynamic Trees + (by supermassimo0310)
When Dungeons Arise (by Aureljz)
YUNG's Better Caves (Forge) (by YUNGNICKYOUNG)
Macaw's Bridges (by sketch_macaw)
Archer's Paradox (by TeamCoFH)
Farmer's Delight (by vectorwing)
Quark (by Vazkii)
AutoRegLib (by Vazkii)
Configured (by MrCrayfish)
Survive (by Stereowalker)
Macaw's Furniture (by sketch_macaw)
Torchmaster (by xalcon)
Architectury API (Forge) (by shedaniel)
AstikorCarts [Horse Carts] (by MennoMax)
Traveler's Backpack (by Tiviacz1337)
Mantle (by mDiyo)
Falling Leaves (Forge) (by Cheaterpaul)
MrCrayfish's Furniture Mod (by MrCrayfish)
Valhelsia Core (by ValhelsiaTeam)
Biomes O' Plenty (by Forstride)
Macaw's Paintings (by sketch_macaw)
Chunk Animator (by Lumien231)
Blood Magic (by WayofTime)
YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)
Enchantment Descriptions (by DarkhaxDev)
SwingThroughGrass (by exidex)
AttributeFix (by DarkhaxDev)
Behgameon RPG Additions (by DEMMERS)
LibX (by noeppinoeppi)
Doggy Talents (by percivalalb)
Dungeons Mod (by dainxt)
Kotlin for Forge (by thedarkcolour)
Whisperwoods (by itsmeowdev)
Ars Nouveau (by baileyholl2)
End Remastered (by jack_bagel)
AppleSkin (by squeek502)
Village Spawn Point (by Serilum)
Apotheosis (by Shadows_of_Fire)
Bountiful (by ejektaflex)
Guard Villagers (by almightytallestred)
The Twilight Forest (by Benimatic)
Double Slabs (by CJMinecraft01)
No Hostiles Around Campfire (by Serilum)
Just Enough Items (JEI) (by mezz)
Iron Chests (by ProgWML6)
Cloth Config API (Forge) (by shedaniel)
Mutant Beasts (by Chumbanotz)
Macaw's Windows (by sketch_macaw)
Mowzie's Mobs (by bobmowzie)
Caelus API (Forge) (by TheIllusiveC4)
Patchouli (by Vazkii)
MineColonies (by H3lay)
Charm Reforged (by svenhjol)
Origins (Forge) (by EdwinMindcraft)
Macaw's Doors (by sketch_macaw)
Pam's HarvestCraft 2 - Crops (by pamharvestcraft)
Macaw's Trapdoors (by sketch_macaw)
Neoelfeo's Medieval decoration (by neoelfe0)
Pam's HarvestCraft 2 - Food Core (by pamharvestcraft)
Supplementaries (by MehVahdJukaar)
Spartan Shields (by ObliviousSpartan)
Valhelsia Structures (by ValhelsiaTeam)
Decorative Blocks (by stohun)
Mouse Tweaks (by YaLTeR)
Inspirations (by KnightMiner)
Dynamic Surroundings (by OreCruncher)
Doctor Who - Weeping Angels (Forge) (by Suff99)
Chisels & Bits (by AlgorithmX2)
Dynamic Trees (by ferreusveritas)
GeckoLib (by ThanosGecko)
Inventory HUD+ (by dmitrylovin)
Villager Names (by Serilum)
Camels (by talhanation)
Citadel (by alex1the1666)
Nature's Compass (by Chaosyr)
Macaw's Fences and Walls (by sketch_macaw)
Curious Armor Stands (by ochotonida)
Goblin Traders (by MrCrayfish)
BetterEnd (Forge) (by Beethoven92)
Spiders 2.0 (by TheCyberBrick)
Better Animals Plus (by cybercat5555)
GuardsCraft (by sgtmattbaker)
Hardcore Revival (by BlayTheNinth)
Traveler's Index (by idrae_)

**Comment by robinotwilliams** [comment] 2021-05-04 14:07
EDIT: It has nothing to do with incompability, even with just this mod enabled on Forge 36.1.0 (Client/Server) I still can't harvest trees. It works in singleplayer, but not in multiplayer. 
It worked for a short time when I disconnected, created a new singelplayer world and then reconnected, but now it's again unbreakable.

**Comment by lebanni** [comment] 2021-05-04 14:17
I can confirm this issue. I'm Heisenberg on discord. Also, trees do not drop seeds or acorns.

**Comment by Harleyoc1** [comment] 2021-05-04 15:52
Yep, we've heard multiple reports of this on the Discord and are working on a fix.

**Comment by Harleyoc1** [comment] 2021-05-04 18:00
> I can confirm this issue. I'm Heisenberg on discord. Also, trees do not drop seeds or acorns.

@lebanni 
I imagine the trees not dropping seeds is caused by the season compatibility since it majorly tones down drops off-season at the moment.

**Comment by Harleyoc1** [comment] 2021-05-04 18:01
You can turn it off in the config if you want. At some point in the future I will make it fully configurable so you can customise how much different seasons effect different types of trees and such.

**Comment by Harleyoc1** [comment] 2021-05-04 20:03
Fixed in dec9c0a4cf355fb6ebc85730388d00398ad9db6e.

**Closed as completed by Harleyoc1** 2021-05-04 20:03 UTC
Labels: bug, 1.16.5
