### ISSUE TITLE
Tree generation Issues

### ISSUE THREAD

**Issue by rorAKAian** [ferreusveritas/Dynamic-Trees#640] opened 2021-11-10 19:19 UTC
Hello, I've recently installed the Dynamic Trees mod along with many others to create a private modpack. The trees seem to be generating in a weird way, where they are missing from the trunk to almost all blocks, only leaving leaves or a couple of branch blocks at most. Trees also seem to overtake the space where village blocks should be, cutting through houses and other structures. Some examples below:

![2021-11-10_15 56 04](https://user-images.githubusercontent.com/94075962/141177967-990ceef3-4072-4b87-9333-97a3c9bc1620.png)
![2021-11-10_15 56 17](https://user-images.githubusercontent.com/94075962/141177973-7a519772-f2eb-4707-9868-993684b792dc.png)
![2021-11-10_15 56 36](https://user-images.githubusercontent.com/94075962/141177979-b4c03045-3eee-49b5-bff7-f75f4dbd7f3f.png)
![2021-11-10_15 56 51](https://user-images.githubusercontent.com/94075962/141177984-75264baa-0b35-4d5f-99e9-f3c477cce4b2.png)
![2021-11-10_15 57 29](https://user-images.githubusercontent.com/94075962/141177988-f6d89486-7267-4a22-9a60-c40c6c41c3b3.png)

The mods I'm currently using are the following:

![rfj](https://user-images.githubusercontent.com/94075962/141178242-3657ec19-3213-4a73-ae2b-53eeaecc390c.png)

No crash issues have been happening (so far) thankfully. I've tried to fix these issues by myself, by changing settings in the config files and looking into both open and closed issues here, but to no avail.
Ty for you time and for this amazing mod!

**Comment by Harleyoc1** [comment] 2021-11-10 21:00
The ones near structures is probably the same problem as #493. Others I'm less sure about, but they seem similar to an incompatibility with the cave biomes API mod so I'll assume it is a mod compatibility issue.

**Comment by BastardNeko** [comment] 2021-11-30 22:32
Don't know if this is the place to ask, but what's the progress on the incompatibility fix for cavebiomeapi?

**Comment by TheeMrCheeky** [comment] 2022-01-02 10:19
I have had a very similar issue and here is what I found Forge 36.2.20 CaveBiomeApi bugged trees with Dynamic Trees (Tried both solo but when mixed they cause weird spawns of leaves only)

**Comment by Harleyoc1** [comment] 2022-01-08 10:34
> Don't know if this is the place to ask, but what's the progress on the incompatibility fix for cavebiomeapi?

There hasn't been any progress to my knowledge, although I know that the Cave Biomes API author has looked into this in the past. I'm not sure on the details of this issue or how Caves Biomes API works so not really sure where to start looking for this (I was going to look into it a while ago but wasn't able to find up-to-date sources).

**Comment by Harleyoc1** [comment] 2022-01-08 10:36
Anyway going to close this now as it is a duplicate of #612.

**Closed as completed by Harleyoc1** 2022-01-08 10:36 UTC
Labels: bug, 1.16.5, mod incompatibility
