### ISSUE TITLE
Shaders not working on DT leaves

### ISSUE THREAD

**Issue by GohanClub** [ferreusveritas/Dynamic-Trees#342] opened 2019-10-13 22:17 UTC
On any version of Dynamic Trees, tree leaves are not affected by any shaders effects while vanilla leaves do, no mods are installed except OptiFine_1.12.2_HD_U_E3 and running on forge-1.12.2-14.23.5.2847. I'm using Sildurs Vibrant Shaders v1.23 Extreme-VL shaders, but chocapic's shaders or SEUS wouldnt do either 

I saw another issue where installing betterfoliage corrected the bug but in my case it didnt solve the problem

**Comment by ghost** [comment] 2020-01-23 19:27
It looks like whatever betterfoliage was doing before to fix it has been removed.  We'll need to know how Optifine recognizes a block as leaves.  It's closed source so it might be difficult.

**Comment by ghost** [comment] 2020-01-23 21:24
Had a discussion with @octarine_noise about this problem.  They stated that for the 1.12.2 version of Better Foliage there may be a regression that's causing it to no longer work.  This is not intentional.  It may be some time before it's fixed as their priorities currently lay in 1.14 development.  If the problem stretches out for too long I'll likely consider getting my hands dirty with it.  I use Optifine myself and would like to restore the feature one way or another.

**Comment by Excederus** [comment] 2020-06-01 18:48
*copied over from another issue I posted this in*
Probably a bit late, but Dynamic trees uses a different block ID for it's leaves.
Open up the shader zip and locate the block.properties file.
Open that and scroll to the line where it lists leaves. (if there are 2 lines use the 1.12 one - usually under #else)
Then add "dynamictrees:leaves" after the entries (seperated by a space). (I think it was that block ID. To be sure just look at the leaves ingame with F3 menu on and you can see the ID on the right side)

**Comment by SkeleBones** [comment] 2020-06-03 16:15
> _copied over from another issue I posted this in_
> Probably a bit late, but Dynamic trees uses a different block ID for it's leaves.
> Open up the shader zip and locate the block.properties file.
> Open that and scroll to the line where it lists leaves. (if there are 2 lines use the 1.12 one - usually under #else)
> Then add "dynamictrees:leaves" after the entries (seperated by a space). (I think it was that block ID. To be sure just look at the leaves ingame with F3 menu on and you can see the ID on the right side)

I did what you said but it still isn't working. (block.10018 = leaves leaves2 dynamictrees:leaves dynamictrees:leaves0 dynamictrees:leaves1 dynamictreesbop:leaves_flowering dynamictreesbop:leaves0 dynamictreesbop:leaves1 dynamictreesbop:leaves2 dynamictreesbop:leaves3 dynamictreesbop:leaves4 dynamictreesbop:leaves_palm dynamictreesbop:leaves7 dynamictreesphc:leaves0) This is the # fallback for pre 1.13 versions:
#else one.

**Comment by ghost** [comment] 2020-07-23 02:21
> _copied over from another issue I posted this in_
> Probably a bit late, but Dynamic trees uses a different block ID for it's leaves.
> Open up the shader zip and locate the block.properties file.
> Open that and scroll to the line where it lists leaves. (if there are 2 lines use the 1.12 one - usually under #else)
> Then add "dynamictrees:leaves" after the entries (seperated by a space). (I think it was that block ID. To be sure just look at the leaves ingame with F3 menu on and you can see the ID on the right side)

about this... so I try to save it but it just won't let me save it to the shaderpack? Sorry I just started trying to do this

**Comment by Excederus** [comment] 2020-08-02 14:54
> > _copied over from another issue I posted this in_
> > Probably a bit late, but Dynamic trees uses a different block ID for it's leaves.
> > Open up the shader zip and locate the block.properties file.
> > Open that and scroll to the line where it lists leaves. (if there are 2 lines use the 1.12 one - usually under #else)
> > Then add "dynamictrees:leaves" after the entries (seperated by a space). (I think it was that block ID. To be sure just look at the leaves ingame with F3 menu on and you can see the ID on the right side)
> 
> about this... so I try to save it but it just won't let me save it to the shaderpack? Sorry I just started trying to do this

Hey sorry a bit late again. But it is probably because you are trying to edit the file while inside the zip?
Try with extracting the zip.
Little tip: You can also load shaderpacks when they are not zipped. It just has to be *folder with the shader name*/*shaders*, etc

**Comment by ghost** [comment] 2020-09-02 06:09
Duplicate of #235

**Closed as completed by ghost** 2020-09-02 06:09 UTC
