### ISSUE TITLE
Standart trees in villages

### ISSUE THREAD

**Issue by KostromDan** [ferreusveritas/Dynamic-Trees#622] opened 2021-09-09 12:50 UTC
- Dynamic Trees: lastest
- Forge: lastest
![2021-09-09_15 47 41](https://user-images.githubusercontent.com/90044015/132688864-ceb89451-1abe-4a0f-b1c6-8ad05cce1ce3.png)

**Comment by Harleyoc1** [comment] 2021-09-09 13:28
Duplicate of #518

**Closed as completed by Harleyoc1** 2021-09-09 13:28 UTC
Labels: bug, 1.16.5
