### ISSUE TITLE
Game can´t start with the 1.18.2 version

### ISSUE THREAD

**Issue by BinaryState0** [ferreusveritas/Dynamic-Trees#751] opened 2023-01-11 19:45 UTC
Apparent incompatibility issue but I have not found any kind of culprit, so decided to post here for help.

**Image of game message with error:**
![image](https://user-images.githubusercontent.com/59924473/211902713-a1385beb-5f19-41d5-95ac-2bd8a35a97aa.png)

**Crash log:**
[crash-2023-01-11_16.36.07-fml.txt](https://github.com/DynamicTreesTeam/DynamicTrees/files/10395528/crash-2023-01-11_16.36.07-fml.txt)

**Comment by Harleyoc1** [comment] 2023-01-12 15:46
Duplicate of #747

**Closed as completed by Harleyoc1** 2023-01-12 15:46 UTC
