### ISSUE TITLE
DynamicTrees StackOverflowError Exception ticking world

### ISSUE THREAD

**Issue by lewejajo9** [ferreusveritas/Dynamic-Trees#963] opened 2024-10-26 09:19 UTC
I have a bug that causes my server to crash, and the log is spammed with dynamictrees.block.leaves.DynamicLeavesBlock.updateLeaves(DynamicLeavesBlock.java:208) so i'm posting it here.

Afaik there aren't any particular steps to reproduce, i've been able to play on my server as usual with nothing out of the ordinary happening, going to sleep then waking up to the server being down. The issue seems to occur randomly after some time of the server running.

Server has ModernFix, Noisium, Fastleafdecay, Radium, Starlight, Smoothchunk, ImmediatelyFast, Entityculling, Bocchium, Betterfpsdist, FastSuite, BadOptimizations, FerriteCore, Smoothboot Reloaded, CullLessLeaves Reforged as performance mods, and Terralith, Tectonic, William Wythers Overhauled Overworld,Expanded Ecosphere and Biomes O' Plenty as terraingen modification mods.

I'm also running addons to Dynamic Trees, DT-BiomesoPlenty, DT-Createcompat, DT-Quark and DT-Terralith.
DT-Biomesoplenty mod actually crashed my game in the past one time, i have my base set up near big redwood trees from BoP, and blocks somewhere along the tree got removed (between the base of tree and the leaves) making the top part with leaves just blocks, not dynamictrees trees. There are gaps like that in every redwood tree near me that was chunkloaded at the time.

From what i've checked there are no updates to the DynamicTrees mods i've listed above, and i have DynamicTrees 1.20.1-1.4.0-ALPHA02, DT BOP 1.20.1-3.2.5, DT Quark 1.20.1-2.5.3, DT Terralith 1.20.1-1.2.4, DT Createcompat 1.0.1. I'm also running Forge 47.3.11 on the server.

debug.log and crash log is attached below, with the modlist in debug.log

Crash report: https://gist.github.com/lewejajo9/8460b36262fac7bb27b54ed77ea83c12
debug.log: https://gist.github.com/lewejajo9/023ed248cc2cc3d475870fe03cdeadd4

**Comment by gjerm** [comment] 2024-10-27 18:24
I've seen this happen occasionally too, downgrading to DT 1.3.3 (latest non-alpha version) seems to have fixed it.

**Comment by supermassimo** [comment] 2024-11-27 00:51
Please try ALPHA03 and let me know if this is fixed

**Comment by supermassimo** [comment] 2024-11-27 00:52
duplicate of https://github.com/DynamicTreesTeam/DynamicTrees/issues/956

**Closed as not planned by supermassimo** 2024-11-27 00:52 UTC
Labels: bug, enhancement, 1.20.1, ALPHA
