### ISSUE TITLE
Crash on MC load

### ISSUE THREAD

**Issue by FluffyDiscord** [ferreusveritas/Dynamic-Trees#354] opened 2019-11-02 11:11 UTC
[crash-2019-11-02_12.05.57-client.txt](https://github.com/ferreusveritas/DynamicTrees/files/3800396/crash-2019-11-02_12.05.57-client.txt)

**Describe the bug**
Sudden crash on load

**To Reproduce**
Try to load minecraft

**Additional context**
No idea why is started doing so, i dont remember adding/remove mods or tweaking configs

**Mods List**
mods in crashlog

**Comment by kierajreed** [comment] 2019-11-04 02:23
Please use [pastebin](https://pastebin.com/) for error logs and stack traces.

**Comment by FluffyDiscord** [comment] 2019-11-04 05:55
Here: https://pastebin.com/HXR684TU (I don't understand the difference)

**Comment by kierajreed** [comment] 2019-11-06 02:43
Uploading the file makes us devs need to download it. We don't like downloading random files, so we prefer to be able to view the content on a third part site.

**Comment by kierajreed** [comment] 2019-11-06 02:45
Duplicate of #290. Update Dynamic Trees to 0.9.6.

**Closed as completed by kierajreed** 2019-11-06 02:45 UTC
