### ISSUE TITLE
Server crash on tree felling

### ISSUE THREAD

**Issue by cmat836** [ferreusveritas/Dynamic-Trees#594] opened 2021-07-13 12:47 UTC
**Describe the bug**
Occasionally when a tree is felled, the server closes as the ragdolling tree despawns.

**To Reproduce**
Once when a tree was cut down (dark spruce)
A second time when a player witnessed a burning tree fall (tree type unknown, dead?)

**Screenshots**
None unfortunately, will update with some if players manage to capture it

**Rendering Glitches**
None, but clients are using optifine if that would matter for a server crash?

**Additional context**
This did not occur during my singleplayer testing building the modpack, but once put on a server running with 7 people
it occured twice in 5-6 hours of play with occasional tree felling

**Crashes**
Dynamic trees 1.16.5-0.10.0-Beta17
Dynamic trees BOP 1.16.5-2.0.4
Dynamic trees Quark 1.16.5-2.0.4

first crash : [https://pastebin.com/03B2EsSV](https://pastebin.com/03B2EsSVl)
second crash : [https://pastebin.com/CC98FuLX](https://pastebin.com/CC98FuLX)

**Mods List**
Included in crash list, Forge 1.16.5-36.1.32
Many unfortunately *apologies*

Will update if it crashes again and I get more data

**Comment by Harleyoc1** [comment] 2021-07-13 14:09
Unless the first crash is any different (page is showing 404) this is a coincidence and unrelated to tree felling. Second crash is showing that it's related to the threading world gen bug seemingly caused by some modded dimensions being created off-thread, which I've recently taken some steps to prevent (as of yet unreleased to CF). 

I'm unable to reproduce this bug (it happens rarely, it seems, which would make sense looking at the report). I would appreciate it if you would take a test build of the changes and see if it still crashes after a while.

**Comment by cmat836** [comment] 2021-07-13 22:38
The first crash is identical

I have built a new version based on the current 1.16.5 branch and put it on the server/distributed it to the players (I assume thats okay)

Will keep you updated if there are further crashes

**Comment by Harleyoc1** [comment] 2021-07-16 12:47
I'd appreciate an update on this, due to the lack thereof I assume there have been no further crashes?

**Comment by cmat836** [comment] 2021-07-16 13:38
yeah planned on giving it a couple of days before reporting back, but seems to be fixed. That crash hasn't occurred again, fix worked like a charm it seems.

Thanks for your hard work on this project

**Comment by Harleyoc1** [comment] 2021-07-16 13:51
Thanks for testing this! In that case I'll close this for now, please do re-open if you get any other related crashes.

**Comment by Harleyoc1** [comment] 2021-07-16 13:52
And for anyone else experiencing this it will be included in beta 18 if you're unable to build from the source.

**Closed as completed by Harleyoc1** 2021-07-16 13:51 UTC
Labels: bug, 1.16.5, mod incompatibility
