### ISSUE TITLE
Assistance with tree placement/appearance

### ISSUE THREAD

**Issue by Gaelmare** [ferreusveritas/Dynamic-Trees#405] opened 2020-02-15 08:39 UTC
I'm the developer of a TFC/Dynamic Trees addon. https://www.curseforge.com/minecraft/mc-mods/dynamictreestfc 

I'm struggling with trunk textures. 
In the attached screenshot, the falling tree model has the side texture where the rings should be. The ends of tree branches also have the side textures everywhere.

![2020-02-15_01 35 29](https://user-images.githubusercontent.com/58122689/74584837-b7c2b880-4f93-11ea-9a68-7efbcd7dab63.png)
![2020-02-15_01 34 50](https://user-images.githubusercontent.com/58122689/74584838-b85b4f00-4f93-11ea-8c59-fde854dff19c.png)

Any suggestions? Code at https://github.com/Gaelmare/dynamictreestfc

Thanks!

Dynamic Trees 0.9.7
TFC 0.29.0.115
Forge 1.12.2-14.23.5.2847
MCP stable_39

**Comment by Gaelmare** [comment] 2020-02-16 05:53
Also wouldn't mind some advice on how to avoid trees looking like this:
![2020-02-15_19 56 53](https://user-images.githubusercontent.com/58122689/74676826-1b0b4100-5174-11ea-9881-3580f1a5779d.png)
![2020-02-15_22 52 34](https://user-images.githubusercontent.com/58122689/74676828-1ba3d780-5174-11ea-85ea-a871a65146eb.png)

**Comment by ghost** [comment] 2020-03-13 20:28
Not exactly sure what's going on with the texture issue just yet.  But the reason why the worldgen is producing those frankentrees is that the coded tree models you're using for spawn don't have the proper block boundary radius.  Make sure the JoCodes in the trees assets files have the right integer radius to fully contain the model.

Edit:  Nevermind, I see that you simply copied the trees JoCodes from the main mod, which should work fine for you.

**Comment by ghost** [comment] 2020-03-13 20:38
Are you actually using the provided Poisson Disc algorithm for placement?  If not you're going to have trouble.  The trees will likely often look that way if they aren't perfectly radially spaced.  Feel free to copy the Poisson Disc algorithm and modify it to suit your needs.

**Comment by Gaelmare** [comment] 2020-03-13 21:07
Thanks for the advice. I'm not using the poission disc location algorithm. The tree radius selection is my current challenge. TFC worldgen code selects a tree species and tests individual locations with the treegen code. There is a Flora density number which I've attempted to relate to library radius choice, but I'm not super happy with. 

Do you have a world save with your JoCode library save structures and MCF blocks built in 1.12? JoCodes from the existing libraries don't seem to match some of the TFC species well.
The only one root per branch network is the immediate cause of the broken tree renders, etc. but I get why that restriction exists. The interesting thing is that the isThick trees seem to have the right end textures on the trunks, but the regular trees do not.

**Comment by ghost** [comment] 2020-09-01 17:57
Closing that as the issue is old and you're in the discord channel anyway so we can just work it out.

**Closed as completed by ghost** 2020-09-01 17:57 UTC
