### ISSUE TITLE
Sand block under the cactuse bug

### ISSUE THREAD

**Issue by Zack7292** [ferreusveritas/Dynamic-Trees#161] opened 2018-11-20 01:40 UTC
Hi there! i find a little texture bug when i walk on my little modded desert they are only under cactus modded by you beutifuls mod. the a link to my screen: [https://prnt.sc/lkheki](url)

**Comment by Deshiba** [comment] 2018-11-20 08:33
This is probably a mod conflict. Which other mods do you have in your pack?

**Comment by ghost** [comment] 2018-11-27 15:03
Duplicate of #118

**Closed as completed by ghost** 2018-11-27 15:03 UTC
