### ISSUE TITLE
Minecraft and my Minecraft server crash because of Primitive Mobs Integration.

### ISSUE THREAD

**Issue by BobsterNub** [ferreusveritas/Dynamic-Trees#461] opened 2020-11-07 16:35 UTC
**Describe the bug**
Minecraft crashes after joining a world in singleplayer, or starting a minecraft server (I'm using Aternos).

**To Reproduce**
1. Open Minecraft
2. Make a singleplayer world
3. Wait for the game to crash.

**Screenshots**
Minecraft server crashing:
![image](https://user-images.githubusercontent.com/74108411/98446342-8ee7e200-2125-11eb-95be-d14d37eb8b87.png)

**Rendering Glitches**
I'm not using Optifine, and I'm pretty sure its not a rendering glitch.

**Additional context**
It seems like an Integration issue with Primitive Mobs.

**Crashes**
- I'm running the latest version of Dynamic Trees (Currently 0.9.20).
- I'm running the latest version of the DT Biomes O' Plenty Add-on (Currently 1.4.4)
- I'm not using the DT Thaumcraft Add-on, because I don't have Thaumcraft.
Crash Log: https://mclo.gs/wLa7i0G (I'm using Aternos)

**Mods List**
![image](https://user-images.githubusercontent.com/74108411/98446643-93ad9580-2127-11eb-9128-dcdc50d26106.png)
![image](https://user-images.githubusercontent.com/74108411/98446656-ade77380-2127-11eb-9705-568755177d7e.png)

Im running Forge 1.12.2 14.23.5.2854

**Comment by Harleyoc1** [comment] 2020-11-07 17:57
Duplicate of #460.

**Closed as completed by Harleyoc1** 2020-11-07 17:57 UTC
