### ISSUE TITLE
"DynamicTrees-1.12.2-0.9.5" Crash on Startup

### ISSUE THREAD

**Issue by A-Vladimir** [ferreusveritas/Dynamic-Trees#254] opened 2019-05-01 09:56 UTC
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Dynamic Trees (dynamictrees)
Caused by: java.lang.ArithmeticException: / by zero
[latest.log](https://github.com/ferreusveritas/DynamicTrees/files/3134193/latest.log)

**Comment by kierajreed** [comment] 2019-05-02 02:52
Please use [hastebin](https://hastebin.com/) for error logs and stack traces.

**Comment by XvBUSHvX** [comment] 2019-05-02 04:20
https://paste.dimdev.org/aqudevoxen.mccrash

**Comment by XvBUSHvX** [comment] 2019-05-02 07:00
Follow up.
MC: 1.12.2
Forge: 2836 (Issue encountered on an earlier version, but suggested by mod involved "Apotheosis"

Minimal list of mods to reproduce.

Dynamic Trees 0.9.5
Apotheosis 1.9.4
Placebo 1.6.0 (used by Apotheosis)
Optifine: Encountered w/ "preview_OptiFine_1.12.2_HD_U_E4_pre4"
Additionally tested against "OptiFine_1.12.2_HD_U_E3"

This was tested without VanillaFix for the same outcome, then VanillaFix was added for convenience with the [hastebin (link)](https://paste.dimdev.org/owinayadaw.mccrash) which replicates the above report.

**Comment by A-Vladimir** [comment] 2019-05-02 07:20
An fix for now would be to disable the garden module in Apotheosis Config. 
PS: I posted this log before Apotheosis updated, but i don't think the issue is fixed yet.

**Comment by XvBUSHvX** [comment] 2019-05-02 07:22
Yeah I noticed that in the other thread...kind of a shame..

**Comment by XvBUSHvX** [comment] 2019-05-02 07:25
IDK why optifine has to be involved as well but I'd guess the cacti since DynTrees don't touch sugar cane..

**Comment by A-Vladimir** [comment] 2019-05-02 07:30
I don't have problems with Optifine

**Comment by mindforger** [comment] 2019-05-02 07:57
this looks simply like an oversight or an over optimistic approach
https://github.com/ferreusveritas/DynamicTrees/blob/1.12.2/src/main/java/com/ferreusveritas/dynamictrees/proxy/ClientProxy.java#L101

`PixelBuffer pixbuf = new PixelBuffer(bakedTextureGetter.apply(resloc));`

returns either something smaller than 16 pixel in width, so the following

`PixelBuffer center = new PixelBuffer(u * 8, u * 8);`
 creates an empty Buffer that fails in the following calls with this crash

who exactly is modifying something here so it behaves not as to be expected is on another page, but this should simply be guarded against instead of trusting the input to be right

Recommentdation: Throw an Exception on your own containing a few details on what file fails in this case, because this seems like maybe a broken texture in a resourcepack, it is never checked that the textures are valid expect the resourcelocation being valid

**Comment by kierajreed** [comment] 2019-07-26 20:22
Duplicate of #290.

**Closed as completed** 2019-11-08 04:26 UTC
