### ISSUE TITLE
Crash by Dynamic Trees

### ISSUE THREAD

**Issue by portres** [ferreusveritas/Dynamic-Trees#339] opened 2019-10-13 08:55 UTC
---- Minecraft Crash Report ----
// There are four lights!

Time: 2019-10-13 10:51:31 CEST
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Dynamic Trees (dynamictrees)
Caused by: java.lang.ArithmeticException: / by zero
    at com.ferreusveritas.dynamictrees.client.TextureUtils.avgColors(TextureUtils.java:191)
    at com.ferreusveritas.dynamictrees.client.TextureUtils$PixelBuffer.averageColor(TextureUtils.java:114)
    at com.ferreusveritas.dynamictrees.proxy.ClientProxy.discoverWoodColors(ClientProxy.java:106)
    at com.ferreusveritas.dynamictrees.proxy.ClientProxy.postInit(ClientProxy.java:85)
    at com.ferreusveritas.dynamictrees.DynamicTrees.postInit(DynamicTrees.java:58)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:754)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
    at net.minecraft.client.Minecraft.init(Minecraft.java:535)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 6879291360 bytes (6560 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
  JVM Flags: 12 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8192m -Xms256m -XX:PermSize=256m -XX:+UseG1GC -Xmx8G -Xms8G -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_E3 148 mods loaded, 148 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                    | Version             | Source                                             | Signature                                |
       |:----- |:--------------------- |:------------------- |:-------------------------------------------------- |:---------------------------------------- |
       | LCHIJ | minecraft             | 1.12.2              | minecraft.jar                                      | None                                     |
       | LCHIJ | mcp                   | 9.42                | minecraft.jar                                      | None                                     |
       | LCHIJ | FML                   | 8.0.99.99           | forge-1.12.2-14.23.5.2847.jar                      | None                                     |
       | LCHIJ | forge                 | 14.23.5.2847        | forge-1.12.2-14.23.5.2847.jar                      | None                                     |
       | LCHIJ | ivtoolkit             | 1.3.3-1.12          | minecraft.jar                                      | None                                     |
       | LCHIJ | foamfixcore           | 7.7.4               | minecraft.jar                                      | None                                     |
       | LCHIJ | dsurroundcore         | 3.5.5.0             | minecraft.jar                                      | None                                     |
       | LCHIJ | forgeendertech        | 1.12.2-4.4.24.0     | ForgeEndertech-1.12.2-4.4.24.0-build.0421.jar      | None                                     |
       | LCHIJ | adhooks               | 1.12.2-3.2.2.0      | AdHooks-1.12.2-3.2.2.0-build.0220.jar              | None                                     |
       | LCHIJ | aiimprovements        | 0.0.1.3             | AIImprovements-1.12-0.0.1b3.jar                    | None                                     |
       | LCHIJ | craftstudioapi        | 1.0.0               | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
       | LCHIJ | animania              | 1.7.2               | animania-1.12.2-1.7.2.jar                          | None                                     |
       | LCHIJ | mantle                | 1.12-1.3.3.55       | Mantle-1.12-1.3.3.55.jar                           | None                                     |
       | LCHIJ | inspirations          | 1.12.2-0.2.8        | Inspirations-1.12.2-0.2.8.jar                      | None                                     |
       | LCHIJ | placebo               | 1.6.0               | Placebo-1.12.2-1.6.0.jar                           | None                                     |
       | LCHIJ | apotheosis            | 1.10.4              | Apotheosis-1.12.2-1.10.5.jar                       | None                                     |
       | LCHIJ | applecore             | 3.2.0               | AppleCore-mc1.12.2-3.2.0.jar                       | None                                     |
       | LCHIJ | jei                   | 4.15.0.268          | jei_1.12.2-4.15.0.268.jar                          | None                                     |
       | LCHIJ | appleskin             | 1.0.9               | AppleSkin-mc1.12-1.0.9.jar                         | None                                     |
       | LCHIJ | thedragonlib          | 1.12.2-5.3.0        | thedragonlib-1.12.2-5.3.0.jar                      | None                                     |
       | LCHIJ | armorplus             | 1.12.2-11.25.1.62   | armorplus-1.12.2-11.25.1.62.jar                    | None                                     |
       | LCHIJ | quark                 | r1.6-177            | Quark-r1.6-177.jar                                 | None                                     |
       | LCHIJ | autoreglib            | 1.3-32              | AutoRegLib-1.3-32.jar                              | None                                     |
       | LCHIJ | ichunutil             | 7.2.2               | iChunUtil-1.12.2-7.2.2.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJ | backtools             | 7.0.1               | BackTools-1.12.2-7.0.1.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJ | baubles               | 1.5.2               | Baubles-1.12-1.5.2.jar                             | None                                     |
       | LCHIJ | betterbuilderswands   | 0.11.1              | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar    | None                                     |
       | LCHIJ | bettercaves           | 1.12.2              | bettercaves-1.12.2-1.5.0.jar                       | None                                     |
       | LCHIJ | forgelin              | 1.8.4               | Forgelin-1.8.4.jar                                 | None                                     |
       | LCHIJ | betterfoliage         | 2.2.0               | BetterFoliage-MC1.12-2.2.0.jar                     | None                                     |
       | LCHIJ | betterportals         | 0.3.7               | betterportals-0.3.7.jar                            | None                                     |
       | LCHIJ | bibliocraft           | 2.4.5               | BiblioCraft[v2.4.5][MC1.12.2].jar                  | None                                     |
       | LCHIJ | bibliotheca           | 1.3.6-1.12.2        | bibliotheca-1.3.6-1.12.2.jar                       | None                                     |
       | LCHIJ | blockcraftery         | 1.12.2-1.3.1        | blockcraftery-1.12.2-1.3.1.jar                     | None                                     |
       | LCHIJ | bloodmoon             | 1.5.3               | Bloodmoon-MC1.12.2-1.5.3.jar                       | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHIJ | buildinggadgets       | 2.7.3               | BuildingGadgets-2.7.3.jar                          | None                                     |
       | LCHIJ | carbonado             | 1.5.1               | carbonado-1.5.1-mc1.12.x.jar                       | None                                     |
       | LCHIJ | carryon               | 1.12.2              | CarryOn MC1.12.2 v1.12.2.jar                       | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
       | LCHIJ | chameleon             | 1.12-4.1.3          | Chameleon-1.12-4.1.3.jar                           | None                                     |
       | LCHIJ | ctm                   | MC1.12.2-0.3.3.22   | CTM-MC1.12.2-0.3.3.22.jar                          | None                                     |
       | LCHIJ | chisel                | MC1.12.2-0.2.1.35   | Chisel-MC1.12.2-0.2.1.35.jar                       | None                                     |
       | LCHIJ | chiselsandbits        | 14.33               | chiselsandbits-14.33.jar                           | None                                     |
       | LCHIJ | clienttweaks          | 3.1.11              | ClientTweaks_1.12.2-3.1.11.jar                     | None                                     |
       | LCHIJ | clumps                | 3.1.2               | Clumps-3.1.2.jar                                   | None                                     |
       | LCHIJ | codechickenlib        | 3.2.3.358           | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJ | cyclopscore           | 1.5.0               | CyclopsCore-1.12.2-1.5.0.jar                       | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCHIJ | colossalchests        | 1.7.3               | ColossalChests-1.12.2-1.7.3.jar                    | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCHIJ | cookiecore            | 2.0.0               | cookiecore-1.12-2.0.0.jar                          | 4bbb70ebe391f24f7704e343108a9b21b44c1b10 |
       | LCHIJ | craftingtweaks        | 8.1.9               | CraftingTweaks_1.12.2-8.1.9.jar                    | None                                     |
       | LCHIJ | crafttweaker          | 4.1.19              | CraftTweaker2-1.12-4.1.19.jar                      | None                                     |
       | LCHIJ | ctgui                 | 1.0.0               | CraftTweaker2-1.12-4.1.19.jar                      | None                                     |
       | LCHIJ | crafttweakerjei       | 2.0.3               | CraftTweaker2-1.12-4.1.19.jar                      | None                                     |
       | LCHIJ | customizeddungeonloot | 1.0.3               | Customized-Dungeon-Loot-1.12 -(v.1.0.3).jar        | None                                     |
       | LCHIJ | fastbench             | 1.7.2               | FastWorkbench-1.12.2-1.7.2.jar                     | None                                     |
       | LCHIJ | cyclicmagic           | 1.19.17             | Cyclic-1.12.2-1.19.17.jar                          | None                                     |
       | LCHIJ | ding                  | 1.0.2               | Ding-1.12.2-1.0.2.jar                              | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJ | dungeontactics        | DT-0.16.6           | DungeonTactics-1.12.2-0.16.6.jar                   | None                                     |
       | LCHIE | dynamictrees          | 1.12.2-0.9.2        | DynamicTrees-1.12.2-0.9.2.jar                      | None                                     |
       | LCHI  | csb_ench_table        | 1.1.3               | EnchantingTable-1.12-1.1.3.jar                     | None                                     |
       | LCHI  | enchdesc              | 1.1.15              | EnchantmentDescriptions-1.12.2-1.1.15.jar          | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHI  | enderstorage          | 2.4.6.137           | EnderStorage-1.12.2-2.4.6.137-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHI  | exchangers            | 1.12.2-2.8          | Exchangers-1.12.2-2.8.jar                          | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
       | LCHI  | shadowmc              | 3.8.0               | ShadowMC-1.12-3.8.0.jar                            | None                                     |
       | LCHI  | extrarails            | 1.3.0               | ExtraRails-1.12-1.3.0.jar                          | None                                     |
       | LCHI  | familiarfauna         | 1.0.11              | FamiliarFauna-1.12.2-1.0.11.jar                    | None                                     |
       | LCHI  | farseek               | 2.3.2               | Farseek-1.12-2.3.2.jar                             | None                                     |
       | LCHI  | fastfurnace           | 1.3.1               | FastFurnace-1.12.2-1.3.1.jar                       | None                                     |
       | LCHI  | fencejumper           | 1.0.5               | fencejumper-1.12-1.0.5.jar                         | None                                     |
       | LCHI  | foamfix               | 0.10.7-1.12.2       | foamfix-0.10.7-1.12.2.jar                          | None                                     |
       | LCHI  | friendlyfire          | 1.5.10              | FriendlyFire-1.12.2-1.5.10.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHI  | ftbbackups            | 0.0.0.ftbbackups    | FTBUtilitiesBackups-1.0.0.12.jar                   | None                                     |
       | LCHI  | futureminecraf        | 1.2.1.1             | FutureVersionsV1.2.1.1.jar                         | None                                     |
       | LCHI  | galaxite              | 1.1.2               | galaxite-1.1.2-mc1.12.x.jar                        | None                                     |
       | LCHI  | harvest               | 1.12-1.2.7-20       | Harvest-1.12-1.2.7-20.jar                          | None                                     |
       | LCHI  | heroicarmory          | 1.1.3               | heroicarmory-1.2.0.jar                             | None                                     |
       | LCHI  | hopperducts           | 1.5                 | hopperducts-mc1.12-1.5.jar                         | None                                     |
       | LCHI  | inventorypets         | 2.0.3               | inventorypets-1.12-2.0.3.jar                       | None                                     |
       | LCHI  | ironchest             | 1.12.2-7.0.67.844   | ironchest-1.12.2-7.0.72.847.jar                    | None                                     |
       | LCHI  | itemfilters           | 1.0.3.12            | ItemFilters-1.0.3.12.jar                           | None                                     |
       | LCHI  | jeiintegration        | 1.5.1.36            | jeiintegration_1.12.2-1.5.1.36.jar                 | None                                     |
       | LCHI  | journeymap            | 1.12.2-5.5.5        | journeymap-1.12.2-5.5.5.jar                        | None                                     |
       | LCHI  | jeresources           | 0.9.2.60            | JustEnoughResources-1.12.2-0.9.2.60.jar            | None                                     |
       | LCHI  | keywizard             | 1.12.2-1.7.1        | keywizard-1.12.2-1.7.1.jar                         | None                                     |
       | LCHI  | kleeslabs             | 5.4.12              | KleeSlabs_1.12.2-5.4.12.jar                        | None                                     |
       | LCHI  | laggoggles            | FAT-1.12.2-4.8      | LagGoggles-FAT-1.12.2-4.8.jar                      | None                                     |
       | LCHI  | libraryex             | 1.0.12              | LibraryEx-1.12.2-1.0.12.jar                        | None                                     |
       | LCHI  | literalascension      | 1.12.2-1.0.2.2      | literalascension-1.12.2-2.0.0.0.jar                | None                                     |
       | LCHI  | longfallboots         | 1.2.1a              | longfallboots-1.2.1b.jar                           | None                                     |
       | LCHI  | magicfeather          | @VERSION@           | magicfeather-1.12.1-2.1.0.jar                      | None                                     |
       | LCHI  | mcjtylib_ng           | 3.5.4               | mcjtylib-1.12-3.5.4.jar                            | None                                     |
       | LCHI  | memeinabottle         | 2.1.1               | MemeInABottle-1.12.X-2.1.1.jar                     | None                                     |
       | LCHI  | moreoverlays          | 1.15.1              | moreoverlays-1.15.1-mc1.12.2.jar                   | None                                     |
       | LCHI  | morpheus              | 1.12.2-3.5.106      | Morpheus-1.12.2-3.5.106.jar                        | None                                     |
       | LCHI  | mousetweaks           | 2.10                | MouseTweaks-2.10-mc1.12.2.jar                      | None                                     |
       | LCHI  | llibrary              | 1.7.19              | llibrary-1.7.19-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHI  | mowziesmobs           | 1.5.4               | mowziesmobs-1.5.4.jar                              | None                                     |
       | LCHI  | multimob              | 1.0.5               | multimob-1.0.5.jar                                 | None                                     |
       | LCHI  | naturalbabyanimals    | 1.2.0               | naturalbabyanimals-1.2.0-mc1.12.x.jar              | None                                     |
       | LCHI  | naturescompass        | 1.5.1               | NaturesCompass-1.12.2-1.5.1.jar                    | None                                     |
       | LCHI  | neat                  | 1.4-17              | Neat 1.4-17.jar                                    | None                                     |
       | LCHI  | netherex              | 2.0.15              | NetherEx-1.12.2-2.0.15.jar                         | None                                     |
       | LCHI  | netherportalfix       | 5.3.17              | NetherPortalFix_1.12.1-5.3.17.jar                  | None                                     |
       | LCHI  | norecipebook          | 1.2.1               | noRecipeBook_v1.2.2formc1.12.2.jar                 | None                                     |
       | LCHI  | notenoughwands        | 1.8.1               | notenoughwands-1.12-1.8.1.jar                      | None                                     |
       | LCHI  | oreexcavation         | 1.4.143             | OreExcavation-1.4.143.jar                          | None                                     |
       | LCHI  | oeintegration         | 2.3.4               | oeintegration-2.3.4.jar                            | None                                     |
       | LCHI  | openglider            | @VERSION@           | OpenGlider-1.12.1-1.1.0.jar                        | None                                     |
       | LCHI  | potioncore            | 1.8_for_1.12.2      | PotionCore-1.8_for_1.12.2.jar                      | None                                     |
       | LCHI  | primitivemobs         | 1.2.3a              | primitivemobs-1.2.3a.jar                           | None                                     |
       | LCHI  | qualitytools          | 1.0.7_for_1.12.2    | QualityTools-1.0.7_for_1.12.2.jar                  | None                                     |
       | LCHI  | quarkoddities         | 1                   | QuarkOddities-1.12.2.jar                           | None                                     |
       | LCHI  | railcraft             | 12.0.0              | railcraft-12.0.0.jar                               | a0c255ac501b2749537d5824bb0f0588bf0320fa |
       | LCHI  | randomthings          | 4.2.7.3             | RandomThings-MC1.12.2-4.2.7.3.jar                  | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHI  | reccomplex            | 1.4.8.2             | RecurrentComplex-1.4.8.2.jar                       | None                                     |
       | LCHI  | redstonepaste         | 1.7.5               | redstonepaste-mc1.12-1.7.5.jar                     | None                                     |
       | LCHI  | reptilemod            | 3.8.4               | reptilemod-1.12.2-3.8.4-89.jar                     | None                                     |
       | LCHI  | additionalstructures  | 2.3.0               | Rex's-Additional-Structures-1.12.x-(v.2.3.0).jar   | None                                     |
       | LCHI  | roguelike             | 1.8.0               | RoguelikeDungeons-1.12.2-1.8.0.jar                 | None                                     |
       | LCHI  | ropebridge            | 2.0.5               | ropebridge-1.12-2.0.7.jar                          | None                                     |
       | LCHI  | ruins                 | 17.2                | Ruins-1.12.2.jar                                   | None                                     |
       | LCHI  | rustic                | 1.1.1               | rustic-1.1.1.jar                                   | None                                     |
       | LCHI  | signals               | 1.4.1-30            | Signals-1.12.2-1.4.1-30-universal.jar              | None                                     |
       | LCHI  | snad                  | 1.12.1-1.7.09.16a   | Snad-1.12.1-1.7.09.16a.jar                         | None                                     |
       | LCHI  | soundfilters          | 0.11_for_1.12       | SoundFilters-0.11_for_1.12.jar                     | None                                     |
       | LCHI  | specialmobs           | 1.0.2_for_mc1.12.2  | specialmobs-1.0.2_for_mc1.12.2.jar                 | None                                     |
       | LCHI  | stepup                | 1.0.2-mc1.10-1.12.2 | StepUp-1.0.2-mc1.10-1.12.jar                       | None                                     |
       | LCHI  | stg                   | 1.12.2-1.2.3        | stg-1.12.2-1.2.3.jar                               | None                                     |
       | LCHI  | storagedrawers        | 1.12.2-5.4.0        | StorageDrawers-1.12.2-5.4.0.jar                    | None                                     |
       | LCHI  | strawgolem            | 1.3                 | strawgolem-1.4.1.jar                               | None                                     |
       | LCHI  | streams               | 0.4.7               | Streams-1.12-0.4.7.jar                             | None                                     |
       | LCHI  | telepass              | 1.0                 | TelePass-1.0.jar                                   | None                                     |
       | LCHI  | theoneprobe           | 1.4.28              | theoneprobe-1.12-1.4.28.jar                        | None                                     |
       | LCHI  | thutcore              | 5.21.0              | thutcore-1.12.2-5.21.0.jar                         | None                                     |
       | LCHI  | thutcore_compat       | 1.0                 | thutcore-1.12.2-5.21.0.jar                         | None                                     |
       | LCHI  | torchmaster           | 1.8.0.79            | torchmaster_1.12.2-1.8.0.79.jar                    | 5e9a436b366831c8f54a7e80b015784da69278c6 |
       | LCHI  | ultimate_unicorn_mod  | 1.5.16              | ultimate_unicorn_mod-1.12.2-1.5.16.jar             | None                                     |
       | LCHI  | vanillafix            | 1.0.10-SNAPSHOT     | VanillaFix-1.0.10-99.jar                           | None                                     |
       | LCHI  | vc                    | 5.9.13              | ViesCraft-1.12.2-5.9.13.jar                        | None                                     |
       | LCHI  | vulcanite             | 1.5.2               | vulcanite-1.5.2-mc1.12.x.jar                       | None                                     |
       | LCHI  | waystones             | 4.0.72              | Waystones_1.12.2-4.0.72.jar                        | None                                     |
       | LCHI  | wearablebackpacks     | 3.1.4               | WearableBackpacks-1.12.2-3.1.4.jar                 | None                                     |
       | LCHI  | wildcrops             | 1.0.1               | WildCrops-1.12-1.0.1.jar                           | None                                     |
       | LCHI  | wolfarmor             | 2.2.3.6             | wolfarmor-1.12.2-2.2.3.1798-universal.jar          | None                                     |
       | LCHI  | xpholder              | 2.0.4               | XpHolder-2.0.4-mc1.12.x.jar                        | None                                     |
       | LCHI  | orelib                | 3.5.2.3             | OreLib-1.12.2-3.5.2.3.jar                          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHI  | dsurround             | 3.5.5.0             | DynamicSurroundings-1.12.2-3.5.5.0.jar             | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHI  | vt                    | 1.12.2-1.5.5        | VanillaTweaks-1.12.2-1.5.5.jar                     | None                                     |
       | LCHI  | mysticallib           | 1.12.2-1.3.8        | mysticallib-1.12.2-1.3.8.jar                       | None                                     |
  Loaded coremods (and transformers): ApotheosisCore (Apotheosis-1.12.2-1.10.5.jar)
                                        shadows.ApotheosisTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.7-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
                                        pw.prok.realbench.asm.RBTransformer
                                      CorePlugin (ForgeEndertech-1.12.2-4.4.24.0-build.0421.jar)
                                        
                                      Quark Plugin (Quark-r1.6-177.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
                                        net.fybertech.nwr.NWRTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
                                        lumien.bloodmoon.asm.ClassTransformer
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      LoadingPlugin (RandomThings-MC1.12.2-4.2.7.3.jar)
                                        lumien.randomthings.asm.ClassTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
                                        mods.betterfoliage.loader.BetterFoliageTransformer
                                      IvToolkit (IvToolkit-1.3.3-1.12.jar)
                                        
                                      DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.5.0.jar)
                                        org.orecruncher.dsurround.asm.Transformer
                                      FarseekCoreMod (Farseek-1.12-2.3.2.jar)
                                        farseek.core.FarseekClassTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 436.48' Renderer: 'GeForce RTX 2070/PCIe/SSE2'
  Pulsar/inspirations loaded Pulses: - InspirationsShared (Enabled/Forced)
                                     - InspirationsBuilding (Enabled/Not Forced)
                                     - InspirationsUtility (Enabled/Not Forced)
                                     - InspirationsTools (Enabled/Not Forced)
                                     - InspirationsRecipes (Enabled/Not Forced)
                                     - InspirationsTweaks (Enabled/Not Forced)
                                     - InspirationsShared (Enabled/Forced)
                                     - TheOneProbePlugin (Enabled/Not Forced)
  Suspected Mods: Dynamic Trees (dynamictrees)
  Launched Version: forge-14.23.5.2847
  LWJGL: 2.9.4
  OpenGL: GeForce RTX 2070/PCIe/SSE2 GL version 4.6.0 NVIDIA 436.48, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 8x Intel(R) Core(TM) i7-7740X CPU @ 4.30GHz

**Comment by kierajreed** [comment] 2019-10-13 16:39
Duplicate of #290.

**Closed as completed** 2019-10-13 16:40 UTC

**Comment by portres** [comment] 2019-10-13 16:43
How can I make it work again?

**Comment by kierajreed** [comment] 2019-10-13 16:45
Remove any mods that have bad textures (no alpha value greater than 128) or wait for an update.
