### ISSUE TITLE
Issues with leaves

### ISSUE THREAD

**Issue by SeppukuSenpai7** [ferreusveritas/Dynamic-Trees#551] opened 2021-05-28 20:23 UTC
Birch leaves are unable to change colormap when generated by Dynamic Trees. All other leaves are compatible with Serene Seasons and texture packs in 0.10.0Beta12 for 1.16.5. Birch leaves do not change color when applicable. Dynamic Tree leaves in 0.10.0Beta12 for 1.16.5 do not respond to shader packs or foliage waving.

**Comment by Harleyoc1** [comment] 2021-05-28 22:02
Duplicate of #533.

**Comment by Harleyoc1** [comment] 2021-05-28 22:03
Also about the shader pack foliage waving, we cannot add support for this. That is something the user must add themselves (for modded support). 

This has been discussed extensively on Discord.

**Closed as completed by Harleyoc1** 2021-05-28 22:02 UTC
Labels: bug, duplicate
