### ISSUE TITLE
Invisible Rooty Dirt w/ Mario Mod

### ISSUE THREAD

**Issue by WenXin20** [ferreusveritas/Dynamic-Trees#125] opened 2018-08-31 05:25 UTC
Forge v14.23.4.2757-1.12.2
Dynamic Trees v0.8.1g
[Raycore](https://minecraft.curseforge.com/projects/raycore) v3.1.0.0
[Mario 2](https://minecraft.curseforge.com/projects/mario-mod-2) v3.0.0.11
[CTM](https://minecraft.curseforge.com/projects/ctm) v0.3.2.18
The rooty dirt block is invisible when next to the ground block from the Mario 2 mod. The Mario 2 mod also requires Raycore and CTM.
![2018-08-31_00 17 37](https://user-images.githubusercontent.com/12000593/44894120-dc4da680-acb3-11e8-8dc8-fe11490d6de1.png)

**Comment by ghost** [comment] 2018-08-31 14:09
Oh my god what an eyesore.  I suspect this is a problem interfacing with CTM since it's a case I never considered.

**Comment by WenXin20** [comment] 2018-08-31 14:44
I thought so too.

**Comment by netmc** [comment] 2018-10-01 04:05
I also ran into this with when one of Pam's wee flowers flower grew next to the root block.  I didn't take a screenshot, but it appeared that there was a flower inside the root stump as well. I've only run into it the one time.

**Comment by ghost** [comment] 2018-11-09 18:35
Duplicate of #118

**Closed as completed by ghost** 2018-11-09 18:35 UTC
Labels: suggestion
