### ISSUE TITLE
Bug on the server with generation

### ISSUE THREAD

**Issue by EgorZverev** [ferreusveritas/Dynamic-Trees#628] opened 2021-09-30 22:29 UTC
I have a bug: when I wander around the world, I see that some of the trees are broken. Trees just haven't a trunk. This generation of trees continues with further travel around the world. I would really like to see this mod in my assembly, but because of this bug, I have to delete it. Server's Forge is v. 36.2.2. There is no such problem in a single player game.

Dynamic Trees - Beta24

**Comment by EgorZverev** [comment] 2021-09-30 22:30
I'll add a screenshot later

**Comment by Harleyoc1** [comment] 2021-10-01 15:15
Duplicate of #612

**Comment by EgorZverev** [comment] 2021-10-02 10:32
Tomorrow I will send a screenshot and will add logs

**Comment by EgorZverev** [comment] 2021-10-03 20:38
I installed the mod on a clean server. Then I repeated it with the Biomes O' Plenty mod. The error was not repeated.

I believe you were right, @Harleyoc1 – various mods for generating caves and structures do cause errors in the modification of "Dynamic Trees" when generating a world on the server (and when creating new chunks).

I want to note that the error was noticed by me in released versions of the mod in minecraft 1.12.2, also on the server.

**Comment by Harleyoc1** [comment] 2021-10-04 20:56
Could you name any mods you suspect might have caused this?

**Comment by EgorZverev** [comment] 2021-10-07 14:42
Hello. I will try I will try to check tomorrow what kind of modification caused the problem

**Comment by NannoKato** [comment] 2021-10-13 02:05
I am doing a modpack and I have also had a problem with the generation of the trees, and I think it could be the same problem, but it happens to me in version 1.16.5.

I've been testing mods one by one, to see which one was causing the problem and so far the one causing it is "Darker Depths".
(by naterbobber) [https://www.curseforge.com/minecraft/mc-mods/darker-depths](url)

![image](https://user-images.githubusercontent.com/92292384/137053843-165fc6f6-21d6-4803-bf26-378cf1b02cea.png)

**Comment by Harleyoc1** [comment] 2021-10-13 13:36
Yep, this mod also requires CaveBiomesAPI, same as Caves and Cliffs backport does. That API mod is the root cause.

**Closed as completed** 2021-12-20 02:48 UTC
Labels: bug, 1.16.5, dedicated server
