### ISSUE TITLE
issue with drops

### ISSUE THREAD

**Issue by Late-Night** [ferreusveritas/Dynamic-Trees#314] opened 2019-09-12 19:37 UTC
**Describe the bug**
trees will only drop seed items

**To Reproduce**
cut down a tree in version DynamicTrees-1.12.2-0.9.5.jar
**Screenshots**

**Rendering Glitches**
Are you using Optifine?

**Additional context**
may be something in the Kit Rustica modpack(which i have appended this mod to), but i highly doubt this

**Crashes**
- Are you running the latest version of Dynamic Trees?(Currently 0.9.4)
- If you are using the DT Biome O' Plenty Add-on do you have the latest version?(Currently 1.4.1e)
- If you are using the DT Thaumcraft Add-on do you have the latest version?(Currently 1.4.1e)
If the above mods are current then please submit a full crash log.  The crash log normally contains the names of mods and their versions.  Don't be that guy who submitted a crash report without first checking that the versions are current.

**Mods List**
If your crash log does not contain a list of mods or you have no crash log then please provide a full list of the mods you are using complete with mod versions.
What version of Forge are you running?(e.g. 1.12.2-14.23.5.2768)

**Comment by IdrisQe** [comment] 2019-09-18 06:04
I'm also experiencing this issue. Forge 14.23.5.2847, DT 0.9.5, DTBoP 1.4.1e, DTPHC 1.4.2, DTTC 1.4.1e
No crash, no logs (in both senses of the word log).
I chop down a massive, full-size tree, even with a diamond axe, and seeds, sticks, etc. drop. No logs though. I'm utterly stumped. (tree pun not intended).

I'm not sure if related, but I THINK each time I chopped down a tree, this appeared in the DEBUG log
`[21:49:58] [Server thread/WARN] [net.minecraft.world.WorldServer]: Tried to add entity dynamictrees:falling_tree but it was marked as removed already`

Modlist is as follows:
https://pastebin.com/LHZkbXzZ

**Comment by IdrisQe** [comment] 2019-09-20 00:26
Ah, I've found the cause of my particular issue.
It appears Liquid Luck was somehow responsible for causing the log drops to not work correctly. I have no idea why, as it shouldn't alter any droprates unless you have a luck-altering potion effect, but after much testing, it's the single mod causing this for me. Unfortunately this doesn't help the OP given that their pack doesn't contain said mod.

**Comment by ghost** [comment] 2020-09-01 23:40
No mod list provided.  Likely a mod interaction problem but I can't troubleshoot.  Eliminate suspicious mods to help find the culprit and run a test world.  Resubmit the issue when you find exactly which mod is causing a problem.

**Closed as completed by ghost** 2020-09-01 23:40 UTC
