### ISSUE TITLE
Dynamic Trees - Leaves not waving with (shaders)

### ISSUE THREAD

**Issue by ProtocolArcus** [ferreusveritas/Dynamic-Trees#403] opened 2020-02-08 01:59 UTC
**Describe the bug**
Leaves generated from the Dynamic Trees mod do not wave when using SEUS, but vanilla leaves wave just fine when placed down.

**To Reproduce**
Use Dynamic Trees and SEUS Renewed, or any shaderpack that has waving leaves.

**Rendering Glitches**
Yes I am using Optifine.

**Comment by Excederus** [comment] 2020-06-01 18:44
Probably a bit late, but Dynamic trees uses a different block ID for it's leaves.
Open up the shader zip and locate the block.properties file.
Open that and scroll to the line where it lists leaves. (if there are 2 lines use the 1.12 one - usually under #else) 
Then add "dynamictrees:leaves" after the entries (seperated by a space). (I think it was that block ID. To be sure just look at the leaves ingame with F3 menu on and you can see the ID on the right side)

**Comment by ghost** [comment] 2020-09-02 04:38
duplicate of #235

**Closed as completed by ghost** 2020-09-02 04:38 UTC
