### ISSUE TITLE
Dynamic trees crashing game on startup

### ISSUE THREAD

**Issue by FormalPineapple** [ferreusveritas/Dynamic-Trees#341] opened 2019-10-13 20:50 UTC
https://pastebin.com/0PrG1wRA

**Comment by kierajreed** [comment] 2019-10-13 21:40
Please use [pastebin](https://pastebin.com/) for error logs and stack traces.

**Comment by FormalPineapple** [comment] 2019-10-13 21:47
> Please use [pastebin](https://pastebin.com/) for error logs and stack traces.

My bad. There, I posted it

**Comment by kierajreed** [comment] 2019-10-14 04:13
Duplicate of #290.

**Closed as completed by kierajreed** 2019-10-14 04:13 UTC
