### ISSUE TITLE
Server Crash relating to fireflies from Twilight Forest

### ISSUE THREAD

**Issue by WyattParker** [ferreusveritas/Dynamic-Trees#948] opened 2024-09-25 14:37 UTC
**Rules (Read this first!)**
This is just a template to help you post a useful issue.  Erase these rules and any irrelevant categories and content as you see fit. 

- Only submit issues related to the latest version of the mod for the currently supported version of Minecraft.
- When referring to software versions always use the actual version number and never "latest".
- Use a paste site like [Gist](https://gist.github.com) or [Pastebin](https://pastebin.com) to dump any logs or crash reports. 

If you are opening this **for any other reason** than to report a bug, it will be closed without explanation! For feature requests, use the feature request template. **Do not** open bug reports for add-ons! These should be reported to their respective issue trackers. 

**Describe the bug**
Server crashes, seems to continue to try and generate twilight forest fireflies on trees that are already full.

**To Reproduce**
Steps to reproduce the behavior: Grow a Dynamic Tree variant of the canopy tree, let it get fully grown and wait for the fireflies to generate until there's no more room to make any

**Screenshots**

**Rendering Glitches**
Are you using Sodium (or any equivalent mods that mess with rendering)?
Yes

**Additional context**

**Crashes**
- Are you running the latest version of Dynamic Trees? 1.3.3 
- What addons are you using? PHC2, Quark, Ars Nouveau, Twilight Forest
- Are you on the latest version for each addon? 
- 1.2.0 Ars Nouveau addon
- 1.3.1 PHC2 addon
- 2.5.3 Quark Addon
- 2.2.0-Beta2 Twilight Forest addon

If the above mods are current then please submit a full crash log. The crash log normally contains the names of mods and their versions. 
https://mclo.gs/JZFt4zC

Also, **do not** paste the crash report into the issue body! Use a paste site like [Gist](https://gist.github.com) or [Pastebin](https://pastebin.com).

**Mods List**
If your crash log does not contain a list of mods or you have no crash log then please provide a full list of the mods you are using complete with mod versions.
What version of Forge are you running? (e.g. 1.12.2-14.23.5.2768) 1.20.1- 47.3.10

**Comment by supermassimo** [comment] 2024-09-25 14:40
Duplicate of https://github.com/DynamicTreesTeam/DynamicTrees-TheTwilightForest/issues/1

**Closed as completed by supermassimo** 2024-09-25 14:40 UTC
Labels: bug, enhancement
