### ISSUE TITLE
Wooded Badlands Biome

### ISSUE THREAD

**Issue by Diababloss** [ferreusveritas/Dynamic-Trees#672] opened 2022-02-22 20:41 UTC
Hello!

I'm new about playing modded 1.16 but i spent some time on 1.12 without noticing something similar...

Roaming the woodded badlands biome i found that a lot of trees are still vanilla... Something like half of them. Here's my modlist:

[MODS.ods](https://github.com/DynamicTreesTeam/DynamicTrees/files/8120108/MODS.ods)

**Comment by Harleyoc1** [comment] 2022-02-26 12:10
I can't reproduce this. It's likely one of your mods is adding the trees but unfortunately knowing which one is difficult to diagnose as it's not an issue I'm aware of. 

I would recommend you do binary search style troubleshooting by temporarily removing half the mods on the list, see if it still occurs, and keep repeating until it is narrowed down to a particular mod. I would also recommend you verify first that it does not occur on your game with only DT installed.

**Comment by Harleyoc1** [comment] 2022-03-15 17:00
I'm going to close this for now for reasons mentioned above. If you still think it's an issue then feel free to re-open with new information.

**Closed as completed by Harleyoc1** 2022-03-15 17:00 UTC
Labels: bug, 1.16.5, mod incompatibility, can't reproduce
