### ISSUE TITLE
Crashes Whenever A Falling Tree Does Damage To Anything!

### ISSUE THREAD

**Issue by W0lfk1ng2000** [ferreusveritas/Dynamic-Trees#837] opened 2024-01-19 02:36 UTC
THIS CRASH REPORT IS FOR THE 1.20.1 MINECRAFT VERSION OF THE MOD

Game Crashes whenever a falling tree lands on a mob or player.

I tried changing settings in the Config but no problem was fixed.

I am running the latest version of Optifine for 1.20.1

I am running the latest version of Dynamic Trees for 1.20.1

[gistfile1.txt](https://github.com/DynamicTreesTeam/DynamicTrees/files/13983322/gistfile1.txt)

**Mods List**
Forge 47.2.20 (MC-Version 1.20.1)
advanced enchantments 1.0.2
agape space 1.2.0
ambient sounds 5.3.5
appleskin 2.5.1
archictury 9.1.12
balm 7.1.2
bookshelf 20.1.8
caelus API (Forge/NeoForge) 3.1.0
cloth config API (Fabric/Forge/NeoForge) 11.1.118
Clumps 12.0.0.3
Collective 7.30
Cosmetic Armor Reworked - 1.20.1-v1a
Creative Core 2.11.22
Cucumber Library 7.0.7
Curios API 5.4.7
Dynamic Music Updated 2.3.2
Dynamic Trees 1.3.0-BETA1
Elytra Slot (Fabric/Forge/Quilt) 6.3.0
Enchantment Descriptions 17.0.13
Fantasy Fauna 0.3.1BETA
Fantasy's Furniture 9.0.0
GeckoLib 4.4
GraveStone Mod 1.0.10
Jade 11.7.1
JEI Integration 10.0.0
Journeymap 5.9.18
Journeymap Integration 0.14-45
Just Enough Items (JEI) 15.2.0.27
Just Enough Resources (JER) 1.4.0.238
Just Leveling [Forge] 1.7
Key Lib 1.0.2
Macaw's Bridges 2.1.1
Macaw's Doors 1.1.0
Macaw's Fences and Walls 1.0.7
Macaw's Paintings 1.0.5
Macaw's Paths and Pavings 1.0.3
Macaw's Roofs 2.2.4
Macaw's Trapdoors 1.1.2
Macaw's Windows 2.2.1
Magic Origins 1.20+
Magical Jewlery 1.6.0
Majrusz Library 7.0.3
Majrusz's Enchantments 1.10.6
MCA Reborn 7.5.11
More Axolotl Variants API 1.1.3
More Axolotl Variants Mod 1.2.4
More Chest Variants 1.4.1
More Horse Armor 2.0.0
More Mob Variants 1.2.2
Mystical Agradditions 7.0.2
Mystical Agriculture 7.0.8
No Tree Punching 7.1.0
Ore Excavation 1.13.170
Origins (Forge) 1.10.0.5
Origins++ 2.2
Pam's HarvestCraft 2 - Crops 1.0.3
Pam's HarvestCraft 2 - Food Core 1.0.3
Pam's HarvestCraft 2 - Food Extended 1.0.0
Pehkui 3.7.12
Realistic Bees 3.8
RPG Backpacks 4.0.0
RPG Health System - MC Version 1.20.1
Serene Seasons 9.0.0.46
Serene Seasons Fix 1.0.8
Space Dimensions (Forge) 1.2.0
Storage Drawers 12.0.2
TerraBlender (Forge) 3.0.1.2
The Twilight Forest 4.3.1893
Trample No More 13.0.2
Unique Magic 1.0.0
Waystones 14.1.3
XL Packets 2.1
XP Tome 2.2

**Comment by unixtensor** [comment] 2024-01-21 19:54
+1, crashes my dedicated server on 1.20.1
![Screenshot_20240120_214045](https://github.com/DynamicTreesTeam/DynamicTrees/assets/80614657/db8ec545-f7e7-486b-a457-5e79cc8b1017)

**Comment by daftinquisitor** [comment] 2024-01-21 20:52
Same error here, mod list follows:

		Aquaculture-1.20.1-2.5.0.jar                      |
		Croptopia-1.20-FORGE-2.3.0.jar                    |
		Cucumber-1.20.1-7.0.0.jar                         |
		DynamicTrees-1.20.1-1.3.0-BETA1.jar               |
		Jade-1.20-forge-11.1.4.jar                        |
		LeavesBeGone-v8.0.0-1.20.1-Forge.jar              |
		MysticalAgradditions-1.20.1-7.0.0.jar             |
		MysticalAgriculture-1.20.1-7.0.0.jar              |
		Patchouli-1.20.1-84-FORGE.jar                     |
		PuzzlesLib-v8.0.2-1.20.1-Forge.jar                |
		REIPluginCompatibilities-forge-12.0.55.jar        |
		RoughlyEnoughItems-12.0.625.jar                   |
		SereneSeasons-1.20.1-9.0.0.43.jar                 |
		Terralith_1.20.x_v2.4.1.jar                       |
		ad_astra-forge-1.20.1-1.15.1.jar                  |
		aether-1.20.1-1.1.0-neoforge.jar                  |
		alexsmobs-1.22.5.jar                              |
		appleskin-forge-mc1.20.1-2.5.0.jar                |
		architectury-9.0.8-forge.jar                      |
		balm-forge-1.20-7.0.4.jar                         |
		botarium-forge-1.20-2.1.0.jar                     |
		citadel-2.4.2-1.20.1.jar                          |
		cloth-config-11.0.99-forge.jar                    |
		comforts-forge-6.3.3+1.20.1.jar                   |
		cookingforblockheads-forge-1.20-16.0.0.jar        |
		coroutil-1.20.1-1.3.0.jar                         |
		corpse-1.20.1-1.0.3.jar                           |
		cosmeticarmorreworked-1.20.1-v1a.jar              |
		cumulus_menus-1.20.1-1.0.0-neoforge.jar           |
		curios-forge-5.3.5+1.20.1.jar                     |
		forge-1.20.1-47.2.20-universal.jar                |
		jmi-forge-1.20.1-0.14-38.jar                      |
		journeymap-1.20.1-5.9.10-forge.jar                |
		mcw-bridges-2.1.1-mc1.20.1forge.jar               |
		mcw-furniture-3.2.1-mc1.20.1forge.jar             |
		mcw-lights-1.0.6-mc1.20.1forge.jar                |
		mcw-roofs-2.2.4-mc1.20.1forge.jar                 |
		mixinextras-forge-0.2.0-beta.9.jar                |
		nitrogen_internals-1.20.1-1.0.1-neoforge.jar      |
		pamhc2crops-1.20-1.0.1.jar                        |
		pamhc2foodcore-1.20-1.0.0.jar                     |
		repurposed_structures-7.0.0+1.20-forge.jar        |
		resourcefulconfig-forge-1.20-2.0.0.jar            |
		resourcefullib-forge-1.20.1-2.1.1.jar             |
		scuba_gear-1.20.1-1.0.6.jar                       |
		seasonhud-1.20.1-1.4.19.jar                       |
		server-1.20.1-20230612.114412-srg.jar             |
		sophisticatedbackpacks-1.20.1-3.18.54.870.jar     |
		sophisticatedcore-1.20.1-0.5.75.338.jar           |
		spectrelib-forge-0.13.12+1.20.1.jar               |
		waystones-forge-1.20-14.0.0.jar                   |
		weather2-1.20.1-2.8.1.jar                         |
		zmedievalmusic-1.20.1-2.1.jar                     |
[crash-2024-01-21_15.31.30-server.txt](https://github.com/DynamicTreesTeam/DynamicTrees/files/14002789/crash-2024-01-21_15.31.30-server.txt)

**Comment by SonicTheHedgehog58987276** [comment] 2024-01-28 19:36
duplicate of #835!

**Comment by supermassimo** [comment] 2024-06-28 20:23
was fixed

**Closed as completed by supermassimo** 2024-06-28 20:23 UTC
Labels: bug
