### ISSUE TITLE
Shaders wont add the waving effect to Dynamic Trees!

### ISSUE THREAD

**Issue by Draglorr** [ferreusveritas/Dynamic-Trees#434] opened 2020-08-15 00:38 UTC
I have been trying to  fix this and i can't seem to figure it out! i personally use SIldurs Enhanced Default! Could i have some help please? i tried adding dynamictrees:leaves to the block>properties folder and it didn't do anything! (1.12.2)

**Comment by KnifeOfDunwall** [comment] 2020-08-20 00:45
I have the same Problem. i use Chocapic 13 V8

**Comment by ghost** [comment] 2020-09-01 17:18
Duplicate of #403

**Closed as completed by ghost** 2020-09-01 17:18 UTC
