### ISSUE TITLE
Spam in server console of "Tried to add entity dynamictrees:falling_tree but it was marked as removed already"

### ISSUE THREAD

**Issue by PenumbraStar** [ferreusveritas/Dynamic-Trees#365] opened 2019-11-23 14:16 UTC
Getting excessive spam of a warning in server console;
[Server thread/WARN] [minecraft/WorldServer]: Tried to add entity dynamictrees:falling_tree but it was marked as removed already

As of right now, loading dynamic trees into a server environment with our mod pack appears to cause this, I have also been experiencing a drastic increase in server resources being used and recently discovered this after getting several entity errors I could not diagnose.

I am running the following mod versions on Minecraft 1.12.2 with forge version 14.23.5.2847;
Dynamic Trees 1.12.2-0.9.6
DT Biome O' Plenty 1.12.2-1.4.1e
DT Pams Harvest Craft 1.4.2
DT Thaumcraft 1.4.1e

However there is no crashing yet.

I will upload a full mod list later today, working on some other back end stuff at the moment and do not have a full list compiled at the moment.

Thank you for your time and creation of this wonderful mod, it makes the world feel much more alive and I would hate to have to remove it because of some weird bug.

**Comment by fatlard1993** [comment] 2019-12-16 21:57
I also see these messages. I have a rather large set of mods, though none that overlap with yours.
https://gist.github.com/fatlard1993/fb7983dc78fb2556f002a99c499d43d6

**Comment by PenumbraStar** [comment] 2019-12-20 13:55
Recently we reset the server, in doing so we removed dynamic trees, prob just gonna keep it out until this is fixed as it has caused a massive amount of tps issues.

**Comment by yrsegal** [comment] 2020-01-06 02:45
This is caused by a very basic mistake.

https://github.com/ferreusveritas/DynamicTrees/blob/45090027fbe6d400949630ad4188169f33739717/src/main/java/com/ferreusveritas/dynamictrees/entities/EntityFallingTree.java#L451-L454

That should never happen. You're not supposed to do anything even remotely like this, and trees *should* be saved to disk when falling.

**Comment by ghost** [comment] 2020-01-06 03:43
Thanks for the good info, I'll look into correcting this.  Do you have any additional reasons as to why it can't be done this way?  Such as why not saving it can cause this problem?

**Comment by yrsegal** [comment] 2020-01-06 04:09
It can't be done this way, because the server never expects to see something die as it's loaded. Doing so causes it to freak out, because there's a discrepancy between what should have resulted from the load and what didn't.

You should never change the state of the object except to make it match what the NBT has, in a read method. They're called by much more than just saving to disk, such as commands and various entity or chunk routines.

**Comment by KiritoSan223** [comment] 2020-01-08 04:51
I'm having this spam too with a similarly large modpack, one thing stood out though: every time this spam occurs all items are being deleted from the ground.

**Comment by ghost** [comment] 2020-01-21 04:35
I just pushed what I believe is a fix for this problem.  I tested it and it seems to work fine.  If anyone else can build and test I'd appreciate it.

**Closed as completed** 2020-01-21 15:40 UTC
