### ISSUE TITLE
Tree generation issue (likely incompatibility) [16.5]

### ISSUE THREAD

**Issue by ranenvious** [ferreusveritas/Dynamic-Trees#619] opened 2021-09-05 21:36 UTC
I have been trying to figure out what is causing this issue in my modpack but I have gone through every mod I can think even might be causing it, tried several search queries on it, all with no success.
![2021-09-05_17 27 52](https://user-images.githubusercontent.com/39103942/132141937-8fbfe864-4ea8-4e60-a70e-7f318207b8da.png)
Does anyone know what mod is causing this incompatibility?

(ps : none of these leaves are decaying and I haven't broken or placed a single block in this world yet)

**Comment by Harleyoc1** [comment] 2021-09-05 22:33
Do you have Caves and Cliffs backport installed? I have seen similar screenshots reported relating to that mod (if so there is already an issue open #612).

**Comment by ranenvious** [comment] 2021-09-05 22:59
> Do you have Caves and Cliffs backport installed? I have seen similar screenshots reported relating to that mod (if so there is already an issue open #612).

I saw that claim as well and I did, at the time of capture, have it installed but I removed it, generated a new world, and the issue is still there. I also tried to find the BGcore mod that it was supposedly dependent on that caused the issue but it wasn't there.

**Comment by Harleyoc1** [comment] 2021-09-10 10:03
I believe the issue is caused by their API but according to a changelog it should be fixed. If it's not fixed by removing/updating then please send a mod list.

**Comment by Harleyoc1** [comment] 2021-09-15 20:42
There is another issue open and I'm pretty certain this is the Caves and Cliffs Backport API, so I'm going to take this as a duplicate of #612.

**Closed as completed by Harleyoc1** 2021-09-15 20:42 UTC
Labels: bug, need more info, 1.16.5, mod incompatibility
