### ISSUE TITLE
Every time I step on or break a baby tree, it crashes my game.

### ISSUE THREAD

**Issue by ninjaKATTguy** [ferreusveritas/Dynamic-Trees#674] opened 2022-03-06 16:19 UTC
**Description**
A clear and concise description of what the bug is: Every time I stand on or break a baby tree (e.g. a warped mushroom or planted oak acorn) my game crashes.

**To Reproduce**
Steps to reproduce the behavior: Just stand on or break a baby tree.

**Rendering Glitches**
Are you using OptiFine (or any equivalent mods that mess with rendering)? No.

**Additional context**
Add any other context about the problem here. None.

**Crashes**
[Report](https://gist.github.com/Harleyoc1/d05a5e1e54e01d28f82a1e948e09f4ef)

**Versions**
Include relevant versions below. If this issue relates to add-ons then include their versions too.

- Dynamic Trees: DynamicTrees-1.16.5-0.10.0-Beta33.jar
- Forge: 36.2.22
- Java: idk
- OS: idk

**Comment by Harleyoc1** [comment] 2022-03-15 17:21
I've marked this as mod incompatibility because I can't reproduce it and DT is not mentioned directly in the crash report. It's most likely caused by one of the other mods you have installed.

**Comment by Harleyoc1** [comment] 2022-03-15 17:23
I can't reproduce this so am going to mark it as a mod incompatibility issue on the assumption that is is caused by one of the other mods you have installed. 

The crash report also does not reference the crash being caused directly by DT code.

**Comment by ninjaKATTguy** [comment] 2022-03-15 20:37
Mod incompatibility makes no sense, because I'm playing on a server and it doesn't happen to anyone else.

**Comment by Harleyoc1** [comment] 2022-03-15 21:29
I think you are misunderstanding what I mean by mod incompatibility. It is meaning that this issue is being caused by some sort of compatibility issue with another mod. The fact you're playing on a server doesn't really change that. 

So.. It doesn't happen to any one else on that server. Are you running any additional client-side mods or perhaps a different version of one of the mods from your other players?

**Comment by ninjaKATTguy** [comment] 2022-03-15 21:47
nope.

**Closed as completed** 2022-07-15 04:02 UTC
Labels: bug, 1.16.5, mod incompatibility, can't reproduce
