### ISSUE TITLE
Branch Models 1.16.5

### ISSUE THREAD

**Issue by Aspurgus** [ferreusveritas/Dynamic-Trees#662] opened 2022-01-27 16:40 UTC
**Description**
Trying to variate branch model textures using blockstates will make the branch not render properly

**To Reproduce**
This is the blockstate file for the branch: [here](https://pastebin.com/EtFytx5B) 

**Screenshots**
![2022-01-27_11 38 55](https://user-images.githubusercontent.com/75339765/151403354-2a57ffe0-307f-4cfb-9ef2-be3e410a84a1.png)
![2022-01-27_11 39 00](https://user-images.githubusercontent.com/75339765/151403361-016ef730-445d-4ef6-b626-32beef905e77.png)
![2022-01-27_11 39 06](https://user-images.githubusercontent.com/75339765/151403362-e5fe8f53-344b-4ea7-bf9e-80c15259137d.png)
Regular working tree for reference

Optifine is not present, haven't tested with it

**Additional context**

**Mods List**
-Abnormals Blueprint
-Team Aurora Abundance
-DT
-DT Plus

**Versions**
- Dynamic Trees: Beta 30, Plus Beta 12
- Forge: 36.2.20
- Java: 8
- OS: Windows

**Comment by Harleyoc1** [comment] 2022-01-27 17:49
Unfortunately there's nothing we can do about this. It's actually caused by a Forge issue, but should be fixed anyway when MinecraftForge/MinecraftForge#7827 gets merged.

**Closed as completed by Harleyoc1** 2022-01-27 17:49 UTC
Labels: bug, forge issue, 1.16.5
