### ISSUE TITLE
Cutting down birch trees cause world to crash

### ISSUE THREAD

**Issue by Jollygreen0502** [ferreusveritas/Dynamic-Trees#725] opened 2022-09-13 22:45 UTC
**Description**
Cutting down birch trees cause world to crash with the message Exception in server tick loop

**To Reproduce**
Cut down birch tree

[](https://gist.github.com/Jollygreen0502/7c8df573a217d825da4ce5ebeaa4b2db#file-gistfile1-txt)

**Versions**
Include relevant versions below. If this issue relates to add-ons then include their versions too.

- Dynamic Trees:1.16.5-0.10.0-Beta34
- Forge:36.2.39
- Java: 8
- OS: Windows 10

**Comment by Jollygreen0502** [comment] 2022-09-13 22:47
Sorry It seems I dont know how to add my crash report

**Comment by Jollygreen0502** [comment] 2022-09-13 22:49
https://gist.github.com/Jollygreen0502/7c8df573a217d825da4ce5ebeaa4b2db

**Comment by TMatheusss** [comment] 2022-09-21 22:43
Cutting down some kind of trees cause crash to me too
[crash-2022-09-21_15.54.37-server.txt](https://github.com/DynamicTreesTeam/DynamicTrees/files/9620832/crash-2022-09-21_15.54.37-server.txt)

**Comment by Harleyoc1** [comment] 2022-09-28 18:29
This is caused by PMMO. Duplicate of #720.

**Closed as completed by Harleyoc1** 2022-09-28 18:29 UTC
Labels: bug, 1.16.5
