### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by HentaiHamster** [ferreusveritas/Dynamic-Trees#185] opened 2018-12-24 20:30 UTC
any idea what's happening here? 

minecraft 1.12.2
dynamic trees 0.9.1f

https://pastebin.com/P4wRsshM

**Comment by SkyHawkB** [comment] 2018-12-25 03:49
Possbile duplicate of #183. There's no point to clutter the issue tracker.

**Comment by ghost** [comment] 2018-12-25 16:18
Duplicate of #183

**Closed as completed by ghost** 2018-12-25 16:18 UTC
