### ISSUE TITLE
[1.16.5] Trees get cut off at the borders of previous loaded chunks when saving and reopening the world

### ISSUE THREAD

**Issue by Quizer9O8** [ferreusveritas/Dynamic-Trees#602] opened 2021-08-01 16:30 UTC
**Describe the bug**
I stumbled across this bug by accident when I saved my game and reopened the world because Immersive Railroading was almost making it crash due to some rendering issue. After I reopened the world I noticed on JourneyMap a weird cut off line in trees so I went there to investigate. Unfortunately, it turned out the be just the case and everything that was currently loading in continued as normal but not in the same pattern the trees where placed before anymore. It almost looks like the noise map for trees keeps constantly switching out when saving and reopening the game.

**To Reproduce**
1. Create a new world
2. Locate any biome with a dense amount of trees and go there
3. Load in a few chunks before saving the world and reopen it as soon as it's finished
4. Go to the edge of the previously loaded in chunks and you'll notice most trees that were in a chunk border are strangely cut off

**Screenshots**
![2021-08-01_18 15 39](https://user-images.githubusercontent.com/19509275/127777979-7fdbe034-be24-47e1-8ece-b5826462a518.png)
![2021-08-01_18 14 38](https://user-images.githubusercontent.com/19509275/127777999-0868d291-cef6-43c2-b46b-63a203b1c866.png)
![2021-08-01_18 15 18](https://user-images.githubusercontent.com/19509275/127778002-4593c9a9-dc4b-4dc0-9f11-510dafa757a4.png)
![2021-08-01_18 14 45](https://user-images.githubusercontent.com/19509275/127778007-4d9ebbf7-dcc4-4ced-9d95-9dc0c188a17a.png)
![2021-08-01_18 15 11](https://user-images.githubusercontent.com/19509275/127778008-fba73796-39e3-4256-ac85-1e42e71962e4.png)

**Rendering Glitches**
Immersive Railroading can sometimes cause a weird rendering issue that covers your entire view with weird polygonal structures.
If you don't save the game in time it will eventually crash it.

**Additional context**
Some chunks tend to be entirely empty with no trees populating it when saving and reopening the world.

**Crashes**
None...

**Mods List**
Forge - 36.2.0:
Dynamic Surroundings (dsurround:1.16.4-4.0.4.2), 
Abnormals Core (abnormals_core:3.2.0), 
Biomes O Plenty (biomesoplenty:1.16.5-13.1.0.477), 
Dynamic Trees (dynamictrees:1.16.5-0.10.0-Beta22), 
Dynamic Trees for Biomes o Plenty (dtbop:1.16.5-2.0.6), 
Dynamic Trees for Neapolitan (dtneapolitan:1.16.5-1.0.0), 
Dynamic Trees for TerraForged (dtterraforged:1.16.5-1.0.0), 
Dynamic Trees for Voyage (dtvoyage:0.0.0.1), 
Dynamic Trees Plus (dynamictreesplus:1.16.5-0.1.0-Beta10), 
Dynamic view distance (dynview:1.8), 
Forge (forge:36.2.0), 
Immersive Railroading (immersiverailroading:1.16.5-forge-1.9.0), 
Journeymap (journeymap:5.7.3), 
Kiwi (kiwi:3.5.2), 
Minecraft (minecraft:1.16.5), 
Mod List Paster (modlistpaste:1.2.0), 
Neapolitan (neapolitan:2.1.0), 
Snow! Real Magic! (snowrealmagic:2.5.7), 
Snow Under Trees (snowundertrees:v1.1.4), 
TerraForged (terraforged:0.2.13), 
TrackAPI (trackapi:1.2), 
Universal Mod Core (universalmodcore:1.1.0), 
Voyage (voyage:1.0.3)

**Comment by Harleyoc1** [comment] 2021-08-01 17:33
Duplicate of #508, read more there for a fix.

**Closed as completed by Harleyoc1** 2021-08-01 17:33 UTC
Labels: bug, 1.16.5, vanilla bug
