### ISSUE TITLE
build errors with structures

### ISSUE THREAD

**Issue by DragonAstemirN** [ferreusveritas/Dynamic-Trees#712] opened 2022-08-06 19:14 UTC
Trees spawn between or on top of structures.
trees are generated within the structures branches and leaves.
trees spawn on plowed land appear with a small gap between the tree and the plowed land

**Screenshots**

![2022-08-06_12 13 30](https://user-images.githubusercontent.com/94336869/183262673-6c2c8b58-0289-41dc-a370-74991a07697f.png)
![2022-08-06_12 05 39](https://user-images.githubusercontent.com/94336869/183262717-b3ff98d7-0b32-4261-b0f4-c9f818c106b8.png)
![2022-08-06_12 05 55](https://user-images.githubusercontent.com/94336869/183262763-99dcd3ae-5b64-4e38-bcd4-4e539a25c90a.png)
![2022-08-06_12 11 08](https://user-images.githubusercontent.com/94336869/183262970-7b9d4f65-2c63-4247-b171-6acbdf0a2b59.png)
![2022-08-06_12 12 33](https://user-images.githubusercontent.com/94336869/183263009-53e9d1c3-b6e8-4485-b3f0-348b360af359.png)

**Mods List**
Repurposed structures
when Dungeons Arise
Ice and Fire

**Versions**

- Dynamic Trees: 0.10.0
- Forge:
- Java: 
- OS:

**Comment by Harleyoc1** [comment] 2022-08-07 10:50
Duplicate of #493

**Closed as completed by Harleyoc1** 2022-08-07 10:50 UTC
Labels: bug, 1.16.5
