### ISSUE TITLE
Crash (related to rendering I think)

### ISSUE THREAD

**Issue by ghost** [ferreusveritas/Dynamic-Trees#309] opened 2019-08-25 22:50 UTC
I get this crash after creating a new world and flying around for a bit. It seems to be related to dynamic trees models. I'll attach two crash reports containing the relevant information, but here's the crash in brief from the multiMC log:

[crash-2019-08-25_17.34.40-client.txt](https://github.com/ferreusveritas/DynamicTrees/files/3538771/crash-2019-08-25_17.34.40-client.txt)
[crash-2019-08-25_17.39.56-client.txt](https://github.com/ferreusveritas/DynamicTrees/files/3538772/crash-2019-08-25_17.39.56-client.txt)

[17:39:56] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  Quark Plugin (Quark-r1.6-177.jar)
  AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.16-universal.jar)
  LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  FarseekCoreMod (Farseek-1.12-2.3.2.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 8/25/19 5:39 PM
Description: Tesselating block in world

java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at com.ferreusveritas.dynamictrees.client.QuadManipulator.getSpriteUVFromBlockState(QuadManipulator.java:173)
	at com.ferreusveritas.dynamictrees.client.QuadManipulator.getModelTexture(QuadManipulator.java:139)
	at com.ferreusveritas.dynamictrees.models.loaders.ModelLoaderWrapped$1.createBakedModel(ModelLoaderWrapped.java:70)
	at com.ferreusveritas.dynamictrees.models.blockmodels.ModelBlockWrapped$1.createModel(ModelBlockWrapped.java:34)
	at com.ferreusveritas.dynamictrees.models.bakedmodels.BakedModelWrapped.getWrappedModel(BakedModelWrapped.java:19)
	at com.ferreusveritas.dynamictrees.models.bakedmodels.BakedModelWrapped.func_177555_b(BakedModelWrapped.java:43)
	at net.minecraft.client.renderer.block.model.IBakedModel.isAmbientOcclusion(IBakedModel.java:29)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:43)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:38)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:200)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
	at java.lang.Thread.run(Unknown Source)

**Comment by ghost** [comment] 2019-08-25 23:16
I suspect this crash is related to some change made by Hungry Animals. Strangely enough, I can't reproduce the crash so far after removing that mod.

**Comment by a3626a** [comment] 2019-09-01 08:11
Hi, i'm the developer of Hungry Animals.
Check this issue. https://github.com/ferreusveritas/DynamicTrees/issues/283

I am sure that this crash is related to Dynamic Tree, not Hungry Animals.

**Comment by ghost** [comment] 2019-09-01 19:26
Can you explain why this crash occurs only while Hungry Animals is installed?

**Comment by a3626a** [comment] 2019-09-02 14:09
Unfortunately, I cant. Because this crash also occurs without HA. Please check the issue I refered.

Also ConcurrentModificationError is usually caused by bad loop interation. Most of the time, it is not related to other mods.

If you still strongly believe HA is the cause, reporting more detailed procedure to reproduce crash could be helpful. Like, how long did you fly to crash with HA, and how long can you fly without HA.

**Comment by a3626a** [comment] 2019-09-02 15:09
I check the source code. Nothing to discuss. You don't even need to reproduce this bug.

@ferreusveritas 
This can be useful. It is quite tricky bug. I think just you can avoid using stream. Just find first element using simple for loop and break.
https://stackoverflow.com/questions/49876119/concurrentmodificationexception-while-iterating-through-a-list-but-not-modifying

**Comment by kierajreed** [comment] 2019-09-05 20:38
Duplicate of #283.

**Closed as completed by kierajreed** 2019-09-05 20:38 UTC
